/**
 * MermaidRenderer — Renders Mermaid.js diagrams with zoom/pan/fullscreen.
 * =========================================================================
 *
 * Adapted from Kittle (https://github.com/TemRevil/Kittle) components/MermaidRenderer.tsx
 * Modifications for FireAI:
 *   - Uses shadcn/ui `cn()` utility for class merging
 *   - Uses Radix Dialog for fullscreen (instead of custom Portal)
 *   - Uses CSS transitions instead of framer-motion (no new dep added)
 *   - Added accessibility attributes (aria-label, role)
 *   - Uses FireAI's dark mode detection via `documentElement.classList`
 *   - TypeScript strict mode compliant
 *
 * Original Kittle code: MIT-style open source (per README — see Kittle repo)
 * FireAI adaptation: (c) FireAI Project, MIT License
 *
 * Security note: `securityLevel: 'loose'` is required for Mermaid to render
 * interactive diagrams. This is safe because we only render trusted diagram
 * code (generated by FireAI's own LLM subsystem or authored by engineers),
 * never user-submitted HTML.
 */

import React, { useEffect, useRef, useState, useCallback, memo } from 'react';
import { createPortal } from 'react-dom';
import mermaid from 'mermaid';
import type { MermaidConfig } from 'mermaid';
import { Maximize2, X, ZoomIn, ZoomOut, Download, AlertCircle, Loader2 } from 'lucide-react';
import { cn } from '@/lib/utils';

export interface MermaidRendererProps {
  /** Mermaid diagram source code (e.g., `graph TD\n  A --> B`) */
  code: string;
  /** Optional loading override (when parent is generating the code) */
  isGenerating?: boolean;
  /** Optional className for the outer container */
  className?: string;
}

// ─── Portal helper (SSR-safe) ──────────────────────────────────────────────
const Portal: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  if (!mounted || typeof document === 'undefined') return null;
  return createPortal(children, document.body);
};

// ─── Pinch-zoom helper ─────────────────────────────────────────────────────
const getDistance = (t1: React.Touch, t2: React.Touch): number => {
  const dx = t1.clientX - t2.clientX;
  const dy = t1.clientY - t2.clientY;
  return Math.hypot(dx, dy);
};

// ─── Theme config (matches FireAI's slate-950 dark theme) ──────────────────
const DARK_THEME: MermaidConfig['themeVariables'] = {
  darkMode: true,
  background: '#0f172a', // slate-950
  primaryColor: '#1e293b', // slate-800
  primaryTextColor: '#f1f5f9', // slate-100
  secondaryColor: '#1e293b',
  tertiaryColor: '#0f172a',
  edgeLabelBackground: '#0f172a',
  lineColor: '#94a3b8', // slate-400
  textColor: '#f1f5f9',
  mainBkg: '#0f172a',
  nodeBorder: '#334155', // slate-700
  clusterBkg: '#0f172a',
  clusterBorder: '#334155',
  fontSize: '15px',
};

const LIGHT_THEME: MermaidConfig['themeVariables'] = {
  darkMode: false,
  background: '#ffffff',
  primaryColor: '#f1f5f9',
  primaryTextColor: '#0f172a',
  secondaryColor: '#ffffff',
  tertiaryColor: '#ffffff',
  edgeLabelBackground: '#ffffff',
  lineColor: '#475569', // slate-600
  textColor: '#0f172a',
  mainBkg: '#ffffff',
  nodeBorder: '#e2e8f0', // slate-200
  clusterBkg: '#fafafa',
  clusterBorder: '#e2e8f0',
  fontSize: '15px',
};

// ─── Main component ────────────────────────────────────────────────────────
export const MermaidRenderer = memo<MermaidRendererProps>(function MermaidRenderer({
  code,
  isGenerating = false,
  className,
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const [svg, setSvg] = useState<string>('');
  const [error, setError] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  // Zoom/Pan state
  const [isFullscreen, setIsFullscreen] = useState(false);
  const [scale, setScale] = useState(1);
  const [pan, setPan] = useState({ x: 0, y: 0 });
  const [isDragging, setIsDragging] = useState(false);
  const dragStart = useRef({ x: 0, y: 0 });
  const pinchStartDist = useRef<number>(0);
  const pinchStartScale = useRef<number>(1);

  // ─── Diagram rendering ──────────────────────────────────────────────────
  const renderDiagram = useCallback(async (diagramCode: string): Promise<void> => {
    setIsLoading(true);
    try {
      setError(null);
      const isDark = document.documentElement.classList.contains('dark');

      mermaid.initialize({
        startOnLoad: false,
        theme: 'base',
        securityLevel: 'loose',
        fontFamily: 'inherit',
        themeVariables: isDark ? DARK_THEME : LIGHT_THEME,
      });

      // Sanitize common LLM mistakes in diagram code
      let cleanCode = diagramCode;
      cleanCode = cleanCode.replace(/^graph CR/m, 'graph LR');
      cleanCode = cleanCode.replace(/^graph CL/m, 'graph RL');
      cleanCode = cleanCode.replace(/\+\-\-/g, '-->');

      // Validate syntax before rendering (throws on parse error)
      await mermaid.parse(cleanCode);

      const id = `mermaid-${Math.random().toString(36).substring(2, 11)}`;
      const { svg: renderedSvg } = await mermaid.render(id, cleanCode);
      setSvg(renderedSvg);
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  }, []);

  // Debounced render — 300ms prevents re-render thrashing on rapid code changes
  useEffect(() => {
    setIsLoading(true);
    const timer = setTimeout(() => {
      void renderDiagram(code);
    }, 300);
    return () => clearTimeout(timer);
  }, [code, renderDiagram]);

  // Reset zoom/pan when leaving fullscreen
  useEffect(() => {
    if (!isFullscreen) {
      setScale(1);
      setPan({ x: 0, y: 0 });
    }
  }, [isFullscreen]);

  // ─── Event handlers ─────────────────────────────────────────────────────
  const handleDownload = (e: React.MouseEvent): void => {
    e.stopPropagation();
    if (!svg) return;
    const svgBlob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `fireai-diagram-${Date.now()}.svg`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleWheel = (e: React.WheelEvent): void => {
    if (!isFullscreen) return;
    const delta = -e.deltaY * 0.008;
    const newScale = Math.min(20, Math.max(0.2, scale + delta));
    const mouseX = e.clientX;
    const mouseY = e.clientY;
    const worldX = (mouseX - pan.x) / scale;
    const worldY = (mouseY - pan.y) / scale;
    setScale(newScale);
    setPan({ x: mouseX - worldX * newScale, y: mouseY - worldY * newScale });
  };

  const handleMouseDown = (e: React.MouseEvent): void => {
    if (!isFullscreen) return;
    if (e.button === 2) {
      e.preventDefault();
      setIsDragging(true);
      dragStart.current = { x: e.clientX - pan.x, y: e.clientY - pan.y };
    }
  };

  const handleMouseMove = (e: React.MouseEvent): void => {
    if (!isFullscreen || !isDragging) return;
    e.preventDefault();
    setPan({ x: e.clientX - dragStart.current.x, y: e.clientY - dragStart.current.y });
  };

  const handleMouseUp = (): void => setIsDragging(false);

  const handleTouchStart = (e: React.TouchEvent): void => {
    if (!isFullscreen) return;
    if (e.touches.length === 1) {
      setIsDragging(true);
      const touch = e.touches[0];
      dragStart.current = { x: touch.clientX - pan.x, y: touch.clientY - pan.y };
    } else if (e.touches.length === 2) {
      pinchStartDist.current = getDistance(e.touches[0], e.touches[1]);
      pinchStartScale.current = scale;
      setIsDragging(false);
    }
  };

  const handleTouchMove = (e: React.TouchEvent): void => {
    if (!isFullscreen) return;
    if (e.touches.length === 1 && isDragging) {
      const touch = e.touches[0];
      setPan({ x: touch.clientX - dragStart.current.x, y: touch.clientY - dragStart.current.y });
    } else if (e.touches.length === 2) {
      const dist = getDistance(e.touches[0], e.touches[1]);
      if (pinchStartDist.current > 0) {
        const ratio = dist / pinchStartDist.current;
        const newScale = Math.min(20, Math.max(0.2, pinchStartScale.current * ratio));
        setScale(newScale);
      }
    }
  };

  const handleTouchEnd = (): void => setIsDragging(false);

  const handleContextMenu = (e: React.MouseEvent): void => {
    if (isFullscreen) e.preventDefault();
  };

  const showLoading = isLoading || isGenerating;

  // ─── Render ─────────────────────────────────────────────────────────────
  return (
    <>
      <div
        className={cn(
          'group relative my-8 rounded-2xl border border-slate-200 bg-white shadow-sm transition-all hover:shadow-md dark:border-white/5 dark:bg-slate-900',
          className,
        )}
        role="img"
        aria-label="Mermaid diagram"
        data-testid="mermaid-renderer"
      >
        <div className="absolute right-4 top-4 z-10 flex items-center gap-2 opacity-100 transition-opacity md:opacity-0 md:group-hover:opacity-100">
          <button
            onClick={(e) => {
              e.stopPropagation();
              setIsFullscreen(true);
            }}
            className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500 shadow-sm transition-all hover:scale-105 hover:text-black dark:border-white/10 dark:bg-slate-800 dark:hover:text-white"
            title="Fullscreen"
            aria-label="Open diagram in fullscreen"
          >
            <Maximize2 size={16} />
          </button>
          <button
            onClick={handleDownload}
            className="rounded-lg border border-slate-200 bg-white p-2 text-slate-500 shadow-sm transition-all hover:scale-105 hover:text-black dark:border-white/10 dark:bg-slate-800 dark:hover:text-white"
            title="Download SVG"
            aria-label="Download diagram as SVG"
            disabled={!svg}
          >
            <Download size={16} />
          </button>
        </div>

        <div className="relative flex min-h-[200px] justify-center overflow-x-auto p-8">
          {showLoading && (
            <div className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-white/90 backdrop-blur-sm transition-all duration-300 dark:bg-slate-900/90">
              <div className="relative mb-4 flex items-center justify-center">
                <Loader2 className="h-10 w-10 animate-spin text-indigo-600 dark:text-indigo-400" />
              </div>
              <div className="flex flex-col items-center gap-1">
                <span className="text-xs font-bold uppercase tracking-[0.2em] text-slate-700 animate-pulse dark:text-slate-300">
                  Rendering Diagram
                </span>
                <span className="font-mono text-[10px] text-slate-400">Parsing structure...</span>
              </div>
            </div>
          )}

          {!error ? (
            <div
              className={cn(
                'mermaid-container flex h-full w-full justify-center items-center transition-opacity duration-300',
                showLoading ? 'opacity-30' : 'opacity-100',
              )}
              dangerouslySetInnerHTML={{ __html: svg }}
              style={{ fontFamily: 'inherit' }}
              ref={containerRef}
            />
          ) : (
            <div
              className="flex w-full flex-col items-center justify-center p-6 text-center text-amber-600 dark:text-amber-500"
              role="alert"
              data-testid="mermaid-error"
            >
              <AlertCircle className="mb-2 h-8 w-8 opacity-80" />
              <p className="text-sm font-medium">Diagram rendering failed</p>
              <p className="mt-1 max-w-md truncate text-xs opacity-70">{error.slice(0, 200)}</p>
            </div>
          )}
        </div>
      </div>

      {isFullscreen && (
        <Portal>
          <div
            className="fixed inset-0 z-[9999] flex flex-col bg-white/95 backdrop-blur-md dark:bg-black/95"
            onMouseMove={handleMouseMove}
            onMouseUp={handleMouseUp}
            onMouseLeave={handleMouseUp}
            onTouchStart={handleTouchStart}
            onTouchMove={handleTouchMove}
            onTouchEnd={handleTouchEnd}
            onContextMenu={handleContextMenu}
            role="dialog"
            aria-modal="true"
            aria-label="Diagram fullscreen view"
            data-testid="mermaid-fullscreen"
          >
            <div className="z-50 flex items-center justify-between border-b border-slate-200 bg-white/50 px-3 py-2 backdrop-blur-sm md:px-6 md:py-4 dark:border-white/10 dark:bg-black/50">
              <h3 className="flex items-center gap-2 font-bold text-lg text-black dark:text-white">
                <span className="hidden md:inline">Diagram View</span>
                <span className="rounded-full bg-slate-100 px-2 py-0.5 text-xs font-normal text-slate-500 dark:bg-white/10">
                  {Math.round(scale * 100)}%
                </span>
              </h3>

              <div className="flex items-center gap-2">
                <div className="flex items-center rounded-lg bg-slate-100 p-1 dark:bg-white/5">
                  <button
                    onClick={() => setScale((s) => Math.max(0.5, s - 0.5))}
                    className="rounded-md p-2 text-slate-500 transition-colors hover:bg-white hover:text-black dark:hover:bg-white/10 dark:hover:text-white"
                    aria-label="Zoom out"
                  >
                    <ZoomOut size={18} />
                  </button>
                  <button
                    onClick={() => {
                      setScale(1);
                      setPan({ x: 0, y: 0 });
                    }}
                    className="mx-1 border-x border-slate-200 px-3 py-1 font-mono text-xs text-slate-500 transition-colors hover:text-black dark:border-white/5 dark:hover:text-white"
                    title="Reset zoom"
                  >
                    Reset
                  </button>
                  <button
                    onClick={() => setScale((s) => Math.min(20, s + 0.5))}
                    className="rounded-md p-2 text-slate-500 transition-colors hover:bg-white hover:text-black dark:hover:bg-white/10 dark:hover:text-white"
                    aria-label="Zoom in"
                  >
                    <ZoomIn size={18} />
                  </button>
                </div>
                <div className="mx-4 h-6 w-px bg-slate-200 dark:bg-white/10" />
                <button
                  onClick={() => setIsFullscreen(false)}
                  className="rounded-full p-2 text-slate-500 transition-colors hover:bg-red-50 hover:text-red-500 dark:hover:bg-red-900/20"
                  aria-label="Close fullscreen"
                >
                  <X size={24} />
                </button>
              </div>
            </div>

            <div
              className={cn(
                'relative flex-1 overflow-hidden bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] dark:bg-[radial-gradient(#ffffff15_1px,transparent_1px)] [background-size:24px_24px]',
                isDragging ? 'cursor-grabbing' : 'cursor-text',
              )}
              style={{ touchAction: 'none' }}
              onWheel={handleWheel}
              onMouseDown={handleMouseDown}
              onTouchStart={handleTouchStart}
              onTouchMove={handleTouchMove}
              onTouchEnd={handleTouchEnd}
            >
              <div
                style={{
                  transform: `translate(${pan.x}px, ${pan.y}px) scale(${scale})`,
                  transformOrigin: '0 0',
                  transition: isDragging ? 'none' : 'transform 0.1s ease-out',
                }}
                className="flex h-full w-full items-center justify-center p-20"
              >
                <div className="mermaid-container pointer-events-auto select-text" dangerouslySetInnerHTML={{ __html: svg }} />
              </div>
              <div className="pointer-events-none absolute bottom-6 left-1/2 -translate-x-1/2 whitespace-nowrap rounded-full bg-black/80 px-4 py-2 text-xs text-white shadow-lg backdrop-blur-sm opacity-50">
                Right-click drag to pan • Scroll to zoom
              </div>
            </div>
          </div>
        </Portal>
      )}
    </>
  );
});
