{{- if .Values.persistence.data.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fireai.fullname" . }}-data
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fireai.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.data.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
  storageClassName: {{ .Values.persistence.data.storageClass }}
{{- end }}
{{- if .Values.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "fireai.fullname" . }}-logs
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "fireai.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
{{- end }}
