{{- range $name, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "fireai.labels" $ | nindent 4 }}
type: {{ $secret.type | default "Opaque" }}
{{- if $secret.stringData }}
stringData:
  {{- range $key, $value := $secret.stringData }}
  {{ $key }}: {{ $value | required (printf "secret.%s.%s is required" $name $key) | b64enc }}
  {{- end }}
{{- end }}
{{- if $secret.data }}
data:
  {{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
---
{{- end }}
