{{- range $name, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.namespace.name }}
  labels:
    {{- include "fireai.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $service.type }}
  ports:
    {{- toYaml $service.ports | nindent 4 }}
  selector:
    {{- include "fireai.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $name }}
---
{{- end }}
