#!/usr/bin/env python3
# NOSONAR
"""
setup_databases.py — Database Configuration Setup Script
======================================================

Interactive setup script to configure environment variables for:
- PostgreSQL (primary database)
- Qdrant (vector database)
- Neo4j (graph database)
- Redis (cache/database)

This script helps generate a .env file with the proper configuration.
"""

import getpass as _getpass
from pathlib import Path


def prompt_user(message: str, default: str = "", hide_input: bool = False) -> str:
    """Prompt user for input with optional default value."""
    if hide_input:
        user_input = _getpass.getpass(prompt=f"{message}: ").strip()
        if user_input:
            return user_input
        return default

    if default:
        prompt_text = f"{message} (default: {default}): "
    else:
        prompt_text = f"{message}: "

    user_input = input(prompt_text).strip()

    if user_input:
        return user_input
    else:
        return default


def setup_supabase_postgres():
    """Setup Supabase PostgreSQL configuration."""
    print("\n🔧 Setting up Supabase PostgreSQL...")
    print("Visit https://supabase.com to create a free project if you haven't already.")

    supabase_url = prompt_user(
        "Enter your Supabase Project URL (e.g., postgresql://postgres:[YOUR-PASSWORD]@aws-0-us-west-1.pooler.supabase.com:5432/postgres)",
        ""
    )

    return {
        "DATABASE_URL": supabase_url,
        "DIGITAL_TWIN_DB_PATH": "./db/digital_twin.db"  # Fallback
    }


def setup_qdrant():
    """Setup Qdrant vector database configuration."""
    print("\n🔧 Setting up Qdrant Vector Database...")
    print("Visit https://cloud.qdrant.io to create a free account if you haven't already.")

    use_cloud = prompt_user("Use Qdrant Cloud? (y/n)", "n").lower().startswith('y')

    if use_cloud:
        qdrant_url = prompt_user("Enter your Qdrant Cluster URL (e.g., https://your-cluster-url.gcp.qdrant.tech:6333)")
        qdrant_api_key = prompt_user("Enter your Qdrant API Key", "", hide_input=True)
        return {
            "QDRANT_URL": qdrant_url,
            "QDRANT_API_KEY": qdrant_api_key
        }
    else:
        return {
            "QDRANT_HOST": prompt_user("Enter Qdrant Host", "localhost"),
            "QDRANT_PORT": prompt_user("Enter Qdrant Port", "6333"),
            "QDRANT_API_KEY": prompt_user("Enter Qdrant API Key (optional)", "")
        }


def setup_neo4j():
    """Setup Neo4j graph database configuration."""
    print("\n🔧 Setting up Neo4j Graph Database...")
    print("Visit https://neo4j.com/cloud/platform/aura-graph-database/ to create a free AuraDB account if you haven't already.")

    neo4j_uri = prompt_user(
        "Enter your Neo4j URI (e.g., bolt://localhost:7687 or bolt+s://your-instance.databases.neo4j.io:7687)",
        "bolt://localhost:7687"
    )
    neo4j_username = prompt_user("Enter Neo4j Username", "neo4j")
    neo4j_password = prompt_user("Enter Neo4j Password", "", hide_input=True)
    neo4j_database = prompt_user("Enter Neo4j Database Name", "neo4j")

    return {
        "NEO4J_URI": neo4j_uri,
        "NEO4J_USERNAME": neo4j_username,
        "NEO4J_PASSWORD": neo4j_password,
        "NEO4J_DATABASE": neo4j_database
    }


def setup_redis():
    """Setup Redis configuration."""
    print("\n🔧 Setting up Redis Database...")
    print("Visit https://upstash.com to create a free Redis account if you haven't already.")

    use_upstash = prompt_user("Use Upstash Redis? (y/n)", "n").lower().startswith('y')

    if use_upstash:
        redis_url = prompt_user("Enter your Upstash Redis URL (e.g., redis://your-redis-url.upstash.io:37463)")
        return {
            "REDIS_URL": redis_url
        }
    else:
        return {
            "REDIS_HOST": prompt_user("Enter Redis Host", "localhost"),
            "REDIS_PORT": prompt_user("Enter Redis Port", "6379"),
            "REDIS_PASSWORD": prompt_user("Enter Redis Password (optional)", ""),
            "REDIS_DB": prompt_user("Enter Redis Database Number", "0")
        }


def generate_env_file(configs: dict):
    """Generate .env file with the collected configurations."""
    env_content = []
    env_content.append("# Database Configuration for Revit Project")
    env_content.append("# Generated by setup_databases.py")
    env_content.append("")

    # Add all configurations to the .env content
    for key, value in configs.items():
        if value:  # Only add non-empty values
            env_content.append(f"{key}={value}")

    # Add other necessary environment variables
    env_content.append("")
    env_content.append("# Application Configuration")
    env_content.append("# Generate with: python -c 'import secrets; print(secrets.token_urlsafe(32))'")
    env_content.append("FIREAI_API_KEY=")
    env_content.append("FIREAI_ENV=development")

    # Write to .env file
    env_path = Path(".env")
    with open(env_path, "w", encoding="utf-8") as f:
        f.write("\n".join(env_content))

    print(f"\n✅ Configuration saved to {env_path.absolute()}")
    print("💡 Remember to add your API keys and other sensitive information to this file.")


def main():
    """Main setup function."""
    print("🏗️  Revit Project - Multi-Database Setup Assistant")
    print("=" * 50)
    print("\nThis script will help you configure:")
    print("- PostgreSQL (Supabase)")
    print("- Qdrant (Vector database)")
    print("- Neo4j (Graph database)")
    print("- Redis (Cache/database)")

    confirm = prompt_user("\nWould you like to proceed with the setup? (y/n)", "y")
    if not confirm.lower().startswith('y'):
        print("Setup cancelled.")
        return

    # Collect configurations
    configs = {}

    # Setup each database type
    configs.update(setup_supabase_postgres())
    configs.update(setup_qdrant())
    configs.update(setup_neo4j())
    configs.update(setup_redis())

    # Confirm before saving
    print("\n📋 Collected Configuration:")
    for key, value in configs.items():
        if value and "PASSWORD" not in key and "KEY" not in key and "SECRET" not in key:
            print(f"  {key}={value}")
        elif value:
            print(f"  {key}=***HIDDEN***")

    confirm_save = prompt_user("\nSave these configurations to .env file? (y/n)", "y")
    if confirm_save.lower().startswith('y'):
        generate_env_file(configs)
        print("\n🎉 Database setup complete!")
        print("\nNext steps:")
        print("1. Fill in the FIREAI_API_KEY in the .env file")
        print("2. Review the .env file for accuracy")
        print("3. Run your application with: source .env && python -m backend.app")
    else:
        print("Configuration not saved.")


if __name__ == "__main__":
    main()
