/**
 * helpTopics.ts — Comprehensive help topics (EN + AR)
 *
 * V140 Phase 7: Full user guide with contextual help for every page.
 * Every topic has Arabic + English content.
 */
import type { HelpTopic, HelpTopicId } from './types';

const related = {
  dashboard: ['projects.create', 'reports.generate', 'settings.backend'] as HelpTopicId[],
  projects: ['projects.create', 'projects.manage', 'connections.create', 'reports.generate'] as HelpTopicId[],
  engineering: ['engineering.overview', 'engineering.voltage-drop', 'engineering.cable-sizing', 'engineering.battery', 'reports.generate'] as HelpTopicId[],
  fireAlarm: ['fire-alarm.detector-placement', 'fire-alarm.symbol-library', 'fire-alarm.zone-navigation', 'reports.generate'] as HelpTopicId[],
  autocad: ['autocad.connect', 'autocad.draw', 'autocad.files'] as HelpTopicId[],
  revit: ['revit.connect', 'revit.create', 'revit.elements', 'revit.files'] as HelpTopicId[],
  digitalTwin: ['digital-twin.overview', 'digital-twin.convert', 'digital-twin.config', 'digital-twin.history', 'elements.overview'] as HelpTopicId[],
  reports: ['reports.generate', 'troubleshooting.api', 'troubleshooting.backend'] as HelpTopicId[],
  elements: ['elements.overview', 'connections.create', 'conflicts.overview'] as HelpTopicId[],
  connections: ['connections.create', 'elements.overview', 'conflicts.overview'] as HelpTopicId[],
  conflicts: ['conflicts.overview', 'elements.overview', 'connections.create'] as HelpTopicId[],
  settings: ['settings.backend', 'settings.api-keys', 'troubleshooting.backend', 'troubleshooting.api', 'troubleshooting.auth'] as HelpTopicId[],
  gettingStarted: ['getting-started.quickstart', 'getting-started.api-setup', 'dashboard.overview', 'projects.create'] as HelpTopicId[],
  troubleshooting: ['troubleshooting.backend', 'troubleshooting.api', 'troubleshooting.auth', 'troubleshooting.app-crash'] as HelpTopicId[],
};

export const HELP_TOPICS: Record<HelpTopicId, HelpTopic> = {
  // ═══════════════════════════════════════════════════════════════════════
  // GETTING STARTED
  // ═══════════════════════════════════════════════════════════════════════
  'getting-started.quickstart': {
    id: 'getting-started.quickstart',
    category: 'getting-started',
    titleEn: 'Quick Start Guide',
    titleAr: 'دليل البدء السريع',
    descriptionEn: 'Get up and running with FireAI in 5 minutes. Learn the basic workflow from project creation to report generation.',
    descriptionAr: 'ابدأ مع FireAI في 5 دقائق. تعرف على سير العمل الأساسي من إنشاء المشروع حتى توليد التقارير.',
    stepsEn: [
      'Open the Dashboard to verify the backend is connected (green badge in top bar).',
      'Go to Projects and click "New Project" to create your first fire alarm project.',
      'Navigate to Engineering to calculate voltage drop, battery sizing, and cable sizing.',
      'Use the Fire Alarm Designer to place detectors on your floor plan.',
      'Open the Digital Twin page to convert between AutoCAD (DWG) and Revit (RVT) formats.',
      'Generate compliance reports from the Reports page.',
      'Check the Settings page to configure your API key and engineering standards.',
    ],
    stepsAr: [
      'افتح لوحة التحكم للتحقق من اتصال الخادم الخلفي (شارة خضراء في الشريط العلوي).',
      'اذهب إلى المشاريع وانقر "مشروع جديد" لإنشاء أول مشروع إنذار حريق.',
      'انتقل إلى الهندسة لحساب هبوط الجهد وحجم البطارية وحجم الكابل.',
      'استخدم مصمم إنذار الحريق لوضع الكواشف على مخطط الطابق.',
      'افتح صفحة التوأم الرقمي للتحويل بين صيغ أوتوكاد (DWG) وريفيت (RVT).',
      'ولّد تقارير الامتثال من صفحة التقارير.',
      'تحقق من صفحة الإعدادات لتكوين مفتاح API والمعايير الهندسية.',
    ],
    warningsEn: [
      'You need a valid API key for most operations. Set it in Settings → Security.',
      'The backend must be running at http://localhost:8000 for the frontend to function.',
    ],
    warningsAr: [
      'تحتاج إلى مفتاح API صالح لمعظم العمليات. اضبطه في الإعدادات → الأمان.',
      'يجب أن يعمل الخادم الخلفي على http://localhost:8000 لكي تعمل الواجهة الأمامية.',
    ],
    keywords: ['quickstart', 'guide', 'begin', 'start', 'بدء', 'سريع', 'دليل'],
    relatedTopics: related.gettingStarted,
    navigateTo: '/dashboard',
    contextRoute: '/dashboard',
  },
  'getting-started.api-setup': {
    id: 'getting-started.api-setup',
    category: 'getting-started',
    titleEn: 'API Key Setup',
    titleAr: 'إعداد مفتاح API',
    descriptionEn: 'Configure your API key to authenticate with the backend. Required for all mutating operations (create, update, delete).',
    descriptionAr: 'قم بتكوين مفتاح API للمصادقة مع الخادم الخلفي. مطلوب لجميع عمليات التعديل (إنشاء، تحديث، حذف).',
    stepsEn: [
      'Go to Settings → Security tab.',
      'Enter your API key in the "API Key" field.',
      'The key is stored in sessionStorage (cleared when the tab closes).',
      'Alternatively, set VITE_FIREAI_API_KEY in your .env file for build-time configuration.',
      'Test the connection by clicking "Refresh" on the Dashboard.',
    ],
    stepsAr: [
      'اذهب إلى الإعدادات → تبويب الأمان.',
      'أدخل مفتاح API في حقل "مفتاح API".',
      'يُحفظ المفتاح في sessionStorage (يُمسح عند إغلاق التبويب).',
      'بدلاً من ذلك، اضبط VITE_FIREAI_API_KEY في ملف .env للتكوين وقت البناء.',
      'اختبر الاتصال بالنقر على "تحديث" في لوحة التحكم.',
    ],
    warningsEn: [
      'Never commit your API key to version control.',
      'Session storage is cleared when the browser tab closes — you may need to re-enter the key.',
    ],
    warningsAr: [
      'لا تضع مفتاح API في نظام التحكم بالإصدارات أبداً.',
      'يُمسح التخزين المؤقت عند إغلاق تبويب المتصفح — قد تحتاج لإعادة إدخال المفتاح.',
    ],
    keywords: ['api', 'key', 'auth', 'setup', 'مفتاح', 'مصادقة', 'إعداد'],
    relatedTopics: related.gettingStarted,
    navigateTo: '/settings',
    contextRoute: '/settings',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DASHBOARD
  // ═══════════════════════════════════════════════════════════════════════
  'dashboard.overview': {
    id: 'dashboard.overview',
    category: 'dashboard',
    titleEn: 'Dashboard Overview',
    titleAr: 'نظرة عامة على لوحة التحكم',
    descriptionEn: 'The dashboard provides a quick overview of your projects, devices, system health, and backend connection status.',
    descriptionAr: 'توفر لوحة التحكم نظرة عامة سريعة على مشاريعك وأجهزتك وصحة النظام وحالة اتصال الخادم الخلفي.',
    stepsEn: [
      'The top bar shows backend connection status (green = connected, red = disconnected).',
      'Stat cards show: total projects, active projects, total devices, and system health.',
      'Click "Refresh" to re-check backend health and reload project/device counts.',
      'Device status breakdown shows OK / Warning / Danger counts.',
    ],
    stepsAr: [
      'يعرض الشريط العلوي حالة اتصال الخادم الخلفي (أخضر = متصل، أحمر = غير متصل).',
      'تعرض بطاقات الإحصائيات: إجمالي المشاريع، المشاريع النشطة، إجمالي الأجهزة، وصحة النظام.',
      'انقر "تحديث" لإعادة فحص صحة الخادم الخلفي وإعادة تحميل أعداد المشاريع/الأجهزة.',
      'يعرض تفصيل حالة الأجهزة أعداد: سليم / تحذير / خطر.',
    ],
    warningsEn: [
      'Dashboard counters are only as current as the last successful API call.',
      'If the backend is disconnected, project and device data may be stale.',
    ],
    warningsAr: [
      'تعتمد عدادات لوحة التحكم على آخر استدعاء API ناجح.',
      'إذا كان الخادم الخلفي غير متصل فقد تكون بيانات المشاريع والأجهزة قديمة.',
    ],
    keywords: ['dashboard', 'overview', 'health', 'status', 'لوحة', 'حالة'],
    relatedTopics: related.dashboard,
    navigateTo: '/dashboard',
    contextRoute: '/dashboard',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // PROJECTS
  // ═══════════════════════════════════════════════════════════════════════
  'projects.create': {
    id: 'projects.create',
    category: 'projects',
    titleEn: 'Create a Project',
    titleAr: 'إنشاء مشروع',
    descriptionEn: 'Create a new fire alarm digital twin project with a name, description, and author.',
    descriptionAr: 'أنشئ مشروع توأم رقمي جديد لأنظمة الإنذار بالاسم والوصف ومعلومات المؤلف.',
    stepsEn: [
      'Open Projects from the sidebar.',
      'Click "New Project" button.',
      'Enter a clear project name (required).',
      'Add an optional description and author name.',
      'Click "Create" and wait for the API response.',
      'The new project appears in the project list.',
    ],
    stepsAr: [
      'افتح المشاريع من الشريط الجانبي.',
      'انقر زر "مشروع جديد".',
      'أدخل اسماً واضحاً للمشروع (مطلوب).',
      'أضف وصفاً اختيارياً واسم المؤلف.',
      'انقر "إنشاء" وانتظر استجابة API.',
      'يظهر المشروع الجديد في قائمة المشاريع.',
    ],
    warningsEn: [
      'Project name is required and must be unique.',
      'You need a valid API key to create projects.',
    ],
    warningsAr: [
      'اسم المشروع مطلوب ويجب أن يكون فريداً.',
      'تحتاج إلى مفتاح API صالح لإنشاء المشاريع.',
    ],
    keywords: ['project', 'create', 'new', 'مشروع', 'إنشاء', 'جديد'],
    relatedTopics: related.projects,
    navigateTo: '/projects',
    contextRoute: '/projects',
  },
  'projects.manage': {
    id: 'projects.manage',
    category: 'projects',
    titleEn: 'Manage Projects',
    titleAr: 'إدارة المشاريع',
    descriptionEn: 'View, edit, sync, and delete existing projects. Filter by status and search by name.',
    descriptionAr: 'عرض وتحرير ومزامنة وحذف المشاريع الموجودة. فلترة بالحالة والبحث بالاسم.',
    stepsEn: [
      'Use the search bar to find projects by name.',
      'Filter by status (active, archived, etc.).',
      'Click the sync icon to synchronize project data with the backend.',
      'Click the delete icon to remove a project (requires confirmation).',
      'Click on a project name to view its details.',
    ],
    stepsAr: [
      'استخدم شريط البحث للعثور على المشاريع بالاسم.',
      'فلترة بالحالة (نشط، مؤرشف، إلخ).',
      'انقر أيقونة المزامنة لمزامنة بيانات المشروع مع الخادم الخلفي.',
      'انقر أيقونة الحذف لإزالة مشروع (يتطلب تأكيداً).',
      'انقر على اسم المشروع لعرض تفاصيله.',
    ],
    warningsEn: [
      'Deleting a project is permanent and cannot be undone.',
      'Syncing may take a few seconds for large projects.',
    ],
    warningsAr: [
      'حذف المشروع دائم ولا يمكن التراجع عنه.',
      'قد تستغرق المزامنة بضع ثوانٍ للمشاريع الكبيرة.',
    ],
    keywords: ['manage', 'edit', 'delete', 'sync', 'إدارة', 'تحرير', 'حذف', 'مزامنة'],
    relatedTopics: related.projects,
    navigateTo: '/projects',
    contextRoute: '/projects',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ENGINEERING
  // ═══════════════════════════════════════════════════════════════════════
  'engineering.overview': {
    id: 'engineering.overview',
    category: 'engineering',
    titleEn: 'Engineering Calculations Overview',
    titleAr: 'نظرة عامة على الحسابات الهندسية',
    descriptionEn: 'Perform NFPA 72-compliant engineering calculations: voltage drop, cable sizing, and battery requirements.',
    descriptionAr: 'قم بإجراء حسابات هندسية متوافقة مع NFPA 72: هبوط الجهد، حجم الكابل، ومتطلبات البطارية.',
    stepsEn: [
      'Select the calculation type from the tabs: Voltage Drop, Cable Sizing, or Battery Calculation.',
      'Enter the required input values in the form fields.',
      'The calculation runs automatically via the QOMN API backend.',
      'Results show compliance status with NFPA 72 standards.',
      'Use the results to generate engineering reports.',
    ],
    stepsAr: [
      'اختر نوع الحساب من التبويبات: هبوط الجهد، حجم الكابل، أو حساب البطارية.',
      'أدخل قيم الإدخال المطلوبة في حقول النموذج.',
      'يتم تشغيل الحساب تلقائياً عبر واجهة QOMN API الخلفية.',
      'تعرض النتائج حالة الامتثال لمعايير NFPA 72.',
      'استخدم النتائج لتوليد تقارير هندسية.',
    ],
    warningsEn: [
      'All calculations are safety-critical and must be verified by a licensed engineer.',
      'Results depend on accurate input values — double-check your entries.',
    ],
    warningsAr: [
      'جميع الحسابات حرجة من حيث السلامة ويجب التحقق منها بواسطة مهندس مرخص.',
      'تعتمد النتائج على قيم إدخال دقيقة — تحقق من إدخالاتك مرتين.',
    ],
    keywords: ['engineering', 'calculation', 'nfpa', 'هندسة', 'حساب'],
    relatedTopics: related.engineering,
    navigateTo: '/engineering',
    contextRoute: '/engineering',
  },
  'engineering.voltage-drop': {
    id: 'engineering.voltage-drop',
    category: 'engineering',
    titleEn: 'Voltage Drop Calculation',
    titleAr: 'حساب هبوط الجهد',
    descriptionEn: 'Calculate voltage drop across fire alarm circuits per NFPA 72 §10.14. Ensures terminal voltage ≥ 16V at end-of-line.',
    descriptionAr: 'احسب هبوط الجهد عبر دوائر إنذار الحريق وفقاً لـ NFPA 72 §10.14. يضمن جهد الطرف ≥ 16V عند نهاية الخط.',
    stepsEn: [
      'Enter the current (Amps) drawn by the circuit.',
      'Enter the cable length (meters) from panel to last device.',
      'Enter the cable cross-section size (mm²).',
      'Enter the supply voltage (typically 24V DC).',
      'Select the conductor material (Copper or Aluminum).',
      'The system calculates: voltage drop (V), percentage drop (%), and compliance status.',
      'Green = suitable (<3%), Amber = acceptable (3-5%), Red = excessive (>5%).',
    ],
    stepsAr: [
      'أدخل التيار (أمبير) الذي تسحبه الدائرة.',
      'أدخل طول الكابل (متر) من اللوحة إلى آخر جهاز.',
      'أدخل مقاس المقطع العرضي للكابل (مم²).',
      'أدخل جهد الإمداد (عادة 24V DC).',
      'اختر مادة الموصل (نحاس أو ألمنيوم).',
      'يحسب النظام: هبوط الجهد (V)، نسبة الهبوط (٪)، وحالة الامتثال.',
      'أخضر = مناسب (<3٪)، كهرماني = مقبول (3-5٪)، أحمر = مفرط (>5٪).',
    ],
    warningsEn: [
      'NFPA 72 §10.14.1 requires minimum 16V at device terminals for 24V systems.',
      'Excessive voltage drop (>5%) requires larger cable or shorter runs.',
    ],
    warningsAr: [
      'يتطلب NFPA 72 §10.14.1 حد أدنى 16V عند أطراف الأجهزة لأنظمة 24V.',
      'هبوط الجهد المفرط (>5٪) يتطلب كابلاً أكبر أو مسارات أقصر.',
    ],
    keywords: ['voltage', 'drop', 'nfpa', 'cable', 'جهد', 'هبوط', 'كابل'],
    relatedTopics: related.engineering,
    navigateTo: '/engineering',
    contextRoute: '/engineering',
  },
  'engineering.cable-sizing': {
    id: 'engineering.cable-sizing',
    category: 'engineering',
    titleEn: 'Cable Sizing Calculation',
    titleAr: 'حساب حجم الكابل',
    descriptionEn: 'Determine the appropriate cable size based on load current, ambient temperature, and derating factors.',
    descriptionAr: 'حدد حجم الكابل المناسب بناءً على تيار الحمل ودرجة الحرارة المحيطة وعوامل التصحيح.',
    stepsEn: [
      'Enter the load current (Amps).',
      'Enter the cable run length (meters).',
      'Enter the ambient temperature (°C).',
      'The system calculates: recommended cable size, base ampacity, derating factor, and final ampacity.',
    ],
    stepsAr: [
      'أدخل تيار الحمل (أمبير).',
      'أدخل طول مسار الكابل (متر).',
      'أدخل درجة الحرارة المحيطة (°م).',
      'يحسب النظام: حجم الكابل الموصى به، السعة الأساسية، عامل التصحيح، والسعة النهائية.',
    ],
    warningsEn: [
      'Always round UP to the next standard cable size.',
      'Consider grouping derating when multiple cables share a conduit.',
    ],
    warningsAr: [
      'قرّب دائماً إلى أعلى حجم كابل قياسي تالٍ.',
      'ضع في اعتبارك تصحيح التجميع عند مشاركة كابلات متعددة لمجرى واحد.',
    ],
    keywords: ['cable', 'sizing', 'ampacity', 'derating', 'كابل', 'حجم', 'سعة'],
    relatedTopics: related.engineering,
    navigateTo: '/engineering',
    contextRoute: '/engineering',
  },
  'engineering.battery': {
    id: 'engineering.battery',
    category: 'engineering',
    titleEn: 'Battery Calculation',
    titleAr: 'حساب البطارية',
    descriptionEn: 'Calculate standby and alarm battery capacity per NFPA 72 §10.6. Ensures 24-hour standby + 5-minute alarm.',
    descriptionAr: 'احسب سعة بطارية الاستعداد والإنذار وفقاً لـ NFPA 72 §10.6. يضمن استعداد 24 ساعة + إنذار 5 دقائق.',
    stepsEn: [
      'Enter the number of standby devices and their current draw (mA).',
      'Enter the number of alarm devices and their current draw (mA).',
      'Set the standby duration (default: 24 hours per NFPA 72).',
      'Set the alarm duration (default: 5 minutes per NFPA 72).',
      'The system calculates: total standby current, total alarm current, required capacity (Ah), and recommended battery.',
    ],
    stepsAr: [
      'أدخل عدد أجهزة الاستعداد وسحب تيارها (مللي أمبير).',
      'أدخل عدد أجهزة الإنذار وسحب تيارها (مللي أمبير).',
      'اضبط مدة الاستعداد (افتراضي: 24 ساعة وفقاً لـ NFPA 72).',
      'اضبط مدة الإنذار (افتراضي: 5 دقائق وفقاً لـ NFPA 72).',
      'يحسب النظام: إجمالي تيار الاستعداد، إجمالي تيار الإنذار، السعة المطلوبة (Ah)، والبطارية الموصى بها.',
    ],
    warningsEn: [
      'NFPA 72 §10.6.7.2.1 requires 24-hour standby for most occupancies.',
      'Always include a 20% safety margin in battery sizing.',
    ],
    warningsAr: [
      'يتطلب NFPA 72 §10.6.7.2.1 استعداد 24 ساعة لمعظم الإشغال.',
      'ضع دائماً هامش أمان 20٪ في تحديد حجم البطارية.',
    ],
    keywords: ['battery', 'standby', 'alarm', 'nfpa', 'بطارية', 'استعداد', 'إنذار'],
    relatedTopics: related.engineering,
    navigateTo: '/engineering',
    contextRoute: '/engineering',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // FIRE ALARM
  // ═══════════════════════════════════════════════════════════════════════
  'fire-alarm.detector-placement': {
    id: 'fire-alarm.detector-placement',
    category: 'fire-alarm',
    titleEn: 'Detector Placement',
    titleAr: 'وضع الكواشف',
    descriptionEn: 'Place smoke and heat detectors on your floor plan following NFPA 72 spacing rules.',
    descriptionAr: 'ضع كواشف الدخان والحرارة على مخطط الطابق باتباع قواعد تباعد NFPA 72.',
    stepsEn: [
      'Open the Fire Alarm Designer from the sidebar.',
      'Select a detector type from the Symbol Library (smoke, heat, pull station, etc.).',
      'Click on the canvas to place the detector at the desired location.',
      'Drag detectors to reposition them.',
      'Click a detector to view and edit its properties (location, height, manufacturer, model).',
      'The coverage radius is displayed automatically based on detector type.',
    ],
    stepsAr: [
      'افتح مصمم إنذار الحريق من الشريط الجانبي.',
      'اختر نوع الكاشف من مكتبة الرموز (دخان، حرارة، محطة سحب، إلخ).',
      'انقر على لوحة الرسم لوضع الكاشف في الموقع المطلوب.',
      'اسحب الكواشف لإعادة تموضعها.',
      'انقر على كاشف لعرض وتحرير خصائصه (الموقع، الارتفاع، الشركة المصنعة، الموديل).',
      'يُعرض نطاق التغطية تلقائياً بناءً على نوع الكاشف.',
    ],
    warningsEn: [
      'Smoke detector spacing: max 9.1m (30ft) per NFPA 72 §17.7.3.2.3.1.',
      'Heat detector spacing: max 7.0m (20ft) per NFPA 72 §17.7.3.2.3.1.',
      'Coverage radius = 0.7 × spacing (R = 6.37m for smoke, 4.9m for heat).',
    ],
    warningsAr: [
      'تباعد كاشف الدخان: حد أقصى 9.1م (30 قدم) وفقاً لـ NFPA 72 §17.7.3.2.3.1.',
      'تباعد كاشف الحرارة: حد أقصى 7.0م (20 قدم) وفقاً لـ NFPA 72 §17.7.3.2.3.1.',
      'نطاق التغطية = 0.7 × التباعد (R = 6.37م للدخان، 4.9م للحرارة).',
    ],
    keywords: ['detector', 'placement', 'smoke', 'heat', 'nfpa', 'كاشف', 'وضع', 'دخان', 'حرارة'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm/designer',
    contextRoute: '/fire-alarm',
  },
  'fire-alarm.symbol-library': {
    id: 'fire-alarm.symbol-library',
    category: 'fire-alarm',
    titleEn: 'Symbol Library',
    titleAr: 'مكتبة الرموز',
    descriptionEn: 'Browse and select fire alarm symbols for placement on the canvas.',
    descriptionAr: 'تصفح واختر رموز إنذار الحريق لوضعها على لوحة الرسم.',
    stepsEn: [
      'The Symbol Library panel is on the left side of the Fire Alarm Designer.',
      'Symbols are categorized by type: smoke detectors, heat detectors, pull stations, notification appliances.',
      'Click a symbol to select it, then click on the canvas to place it.',
      'Each symbol has a default coverage radius based on NFPA 72 standards.',
    ],
    stepsAr: [
      'لوحة مكتبة الرموز موجودة على الجانب الأيسر من مصمم إنذار الحريق.',
      'الرموز مصنفة حسب النوع: كواشف دخان، كواشف حرارة، محطات سحب، أجهزة إشعار.',
      'انقر على رمز لتحديده، ثم انقر على لوحة الرسم لوضعه.',
      'لكل رمز نطاق تغطية افتراضي بناءً على معايير NFPA 72.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['symbol', 'library', 'icon', 'رمز', 'مكتبة', 'أيقونة'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm/designer',
    contextRoute: '/fire-alarm',
  },
  'fire-alarm.zone-navigation': {
    id: 'fire-alarm.zone-navigation',
    category: 'fire-alarm',
    titleEn: 'Zone Navigation',
    titleAr: 'تنقل المناطق',
    descriptionEn: 'Navigate through fire alarm zones, panels, and SLC loops using the zone navigator tree.',
    descriptionAr: 'تنقل عبر مناطق إنذار الحريق واللوحات وحلقات SLC باستخدام شجرة متصفح المناطق.',
    stepsEn: [
      'The Zone Navigator is on the left side of the Fire Alarm page.',
      'It shows a tree structure: Project → FACP Panels → SLC Loops → Zones → Devices.',
      'Click a zone to zoom to it on the canvas.',
      'Click a device to select it and view its properties.',
    ],
    stepsAr: [
      'متصفح المناطق موجود على الجانب الأيسر من صفحة إنذار الحريق.',
      'يعرض بنية شجرية: مشروع → لوحات FACP → حلقات SLC → مناطق → أجهزة.',
      'انقر على منطقة للتكبير إليها على لوحة الرسم.',
      'انقر على جهاز لتحديده وعرض خصائصه.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['zone', 'navigation', 'tree', 'panel', 'منطقة', 'تنقل', 'شجرة', 'لوحة'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm',
    contextRoute: '/fire-alarm',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // AUTOCAD
  // ═══════════════════════════════════════════════════════════════════════
  'autocad.connect': {
    id: 'autocad.connect',
    category: 'autocad',
    titleEn: 'Connect to AutoCAD',
    titleAr: 'الاتصال بـ أوتوكاد',
    descriptionEn: 'Establish a COM connection to a running AutoCAD instance or launch a new one.',
    descriptionAr: 'أنشئ اتصال COM مع نسخة أوتوكاد قيد التشغيل أو أطلق نسخة جديدة.',
    stepsEn: [
      'Open the AutoCAD page from the sidebar.',
      'Toggle "Visible window" to show/hide the AutoCAD application window.',
      'Toggle "Force new instance" to always launch a new AutoCAD (skip connecting to existing).',
      'Click "Connect" to establish the connection.',
      'The status badge changes to green when connected.',
      'Click "Disconnect" to release the connection.',
    ],
    stepsAr: [
      'افتح صفحة أوتوكاد من الشريط الجانبي.',
      'بدّل "نافذة مرئية" لإظهار/إخفاء نافذة تطبيق أوتوكاد.',
      'بدّل "فرض نسخة جديدة" لإطلاق أوتوكاد جديد دائماً (تخطي الاتصال بالموجود).',
      'انقر "اتصال" لإنشاء الاتصال.',
      'تتغير شارة الحالة إلى الأخضر عند الاتصال.',
      'انقر "قطع الاتصال" لتحرير الاتصال.',
    ],
    warningsEn: [
      'AutoCAD COM API is only available on Windows (requires pywin32).',
      'On non-Windows systems, the service runs in simulation mode.',
    ],
    warningsAr: [
      'واجهة أوتوكاد COM متاحة فقط على Windows (تتطلب pywin32).',
      'على الأنظمة غير Windows، يعمل الخدمة في وضع المحاكاة.',
    ],
    keywords: ['autocad', 'connect', 'com', 'windows', 'أوتوكاد', 'اتصال'],
    relatedTopics: related.autocad,
    navigateTo: '/autocad',
    contextRoute: '/autocad',
  },
  'autocad.draw': {
    id: 'autocad.draw',
    category: 'autocad',
    titleEn: 'Drawing Tools',
    titleAr: 'أدوات الرسم',
    descriptionEn: 'Draw lines, polylines, circles, and text directly in AutoCAD from the web interface.',
    descriptionAr: 'ارسم خطوطاً وأخطوطاً متعددة ودوائر ونصاً مباشرة في أوتوكاد من الواجهة الإلكترونية.',
    stepsEn: [
      'Open AutoCAD → Draw from the sidebar.',
      'Select the drawing tool tab: Line, Polyline, Circle, or Text.',
      'Enter coordinates in the format x,y,z (e.g. 0,0,0 for origin).',
      'For polyline, separate points with semicolons (e.g. 0,0,0; 100,0,0; 100,50,0).',
      'Optionally specify a layer name.',
      'Click the "Draw" button to execute.',
    ],
    stepsAr: [
      'افتح أوتوكاد → رسم من الشريط الجانبي.',
      'اختر تبويب أداة الرسم: خط، خط متعدد، دائرة، أو نص.',
      'أدخل الإحداثيات بصيغة x,y,z (مثل 0,0,0 لنقطة الأصل).',
      'للخط المتعدد، افصل النقاط بفاصلة منقوطة (مثل 0,0,0; 100,0,0; 100,50,0).',
      'حدد اسم الطبقة اختيارياً.',
      'انقر زر "رسم" للتنفيذ.',
    ],
    warningsEn: [
      'AutoCAD must be connected before drawing.',
      'Coordinates are in the current AutoCAD drawing units (typically millimeters).',
    ],
    warningsAr: [
      'يجب الاتصال بـ أوتوكاد قبل الرسم.',
      'الإحداثيات بوحدات الرسم الحالية في أوتوكاد (عادة مليمترات).',
    ],
    keywords: ['draw', 'line', 'circle', 'text', 'polyline', 'رسم', 'خط', 'دائرة', 'نص'],
    relatedTopics: related.autocad,
    navigateTo: '/autocad/draw',
    contextRoute: '/autocad/draw',
  },
  'autocad.files': {
    id: 'autocad.files',
    category: 'autocad',
    titleEn: 'DWG File Management',
    titleAr: 'إدارة ملفات DWG',
    descriptionEn: 'Read, write, upload, and save DWG files through the AutoCAD COM API.',
    descriptionAr: 'اقرأ واكتب وارفع واحفظ ملفات DWG عبر واجهة أوتوكاد COM API.',
    stepsEn: [
      'To read a DWG: enter the file path and click "Read", or use the upload area.',
      'To upload: drag & drop a .dwg file or click to browse.',
      'To save: click "Save" on the AutoCAD dashboard.',
      'The status card shows current document info when connected.',
    ],
    stepsAr: [
      'لقراءة DWG: أدخل مسار الملف وانقر "قراءة"، أو استخدم منطقة الرفع.',
      'للرفع: اسحب وأفلت ملف .dwg أو انقر للتصفح.',
      'للحفظ: انقر "حفظ" في لوحة تحكم أوتوكاد.',
      'تعرض بطاقة الحالة معلومات المستند الحالي عند الاتصال.',
    ],
    warningsEn: [
      'Large DWG files may take several seconds to process.',
      'File paths must be accessible from the server running the backend.',
    ],
    warningsAr: [
      'قد تستغرق ملفات DWG الكبيرة عدة ثوانٍ للمعالجة.',
      'يجب أن تكون مسارات الملفات قابلة للوصول من الخادم الذي يشغل الخلفية.',
    ],
    keywords: ['dwg', 'file', 'read', 'write', 'upload', 'ملف', 'قراءة', 'كتابة', 'رفع'],
    relatedTopics: related.autocad,
    navigateTo: '/autocad',
    contextRoute: '/autocad',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // REVIT
  // ═══════════════════════════════════════════════════════════════════════
  'revit.connect': {
    id: 'revit.connect',
    category: 'revit',
    titleEn: 'Connect to Revit',
    titleAr: 'الاتصال بـ ريفيت',
    descriptionEn: 'Connect to a running Revit instance via the Revit API or simulation mode.',
    descriptionAr: 'اتصل بنسخة ريفيت قيد التشغيل عبر Revit API أو وضع المحاكاة.',
    stepsEn: [
      'Open the Revit page from the sidebar.',
      'Toggle "Visible window" to control Revit visibility.',
      'Click "Connect" to establish the connection.',
      'The status badge shows connection state.',
      'Use "Disconnect" to release the connection.',
    ],
    stepsAr: [
      'افتح صفحة ريفيت من الشريط الجانبي.',
      'بدّل "نافذة مرئية" للتحكم في ظهور ريفيت.',
      'انقر "اتصال" لإنشاء الاتصال.',
      'تعرض شارة الحالة حالة الاتصال.',
      'استخدم "قطع الاتصال" لتحرير الاتصال.',
    ],
    warningsEn: [
      'Revit API requires Windows + pythonnet (pythonnet>=3.0.0).',
      'Non-Windows systems use simulation mode (returns simulated element IDs).',
    ],
    warningsAr: [
      'يتطلب Revit API نظام Windows + pythonnet (pythonnet>=3.0.0).',
      'الأنظمة غير Windows تستخدم وضع المحاكاة (ترجع معرفات عناصر محاكاة).',
    ],
    keywords: ['revit', 'connect', 'api', 'ريفيت', 'اتصال'],
    relatedTopics: related.revit,
    navigateTo: '/revit',
    contextRoute: '/revit',
  },
  'revit.create': {
    id: 'revit.create',
    category: 'revit',
    titleEn: 'Create Revit Elements',
    titleAr: 'إنشاء عناصر ريفيت',
    descriptionEn: 'Create walls, floors, columns, beams, doors, and windows in the connected Revit document.',
    descriptionAr: 'أنشئ جدراناً وأرضيات وأعمدة وكمرات وأبواباً ونوافذ في مستند ريفيت المتصل.',
    stepsEn: [
      'Open Revit → Create from the sidebar.',
      'Select the element type tab: Wall, Floor, Column, Beam, Door, or Window.',
      'Enter coordinates and parameters for the element.',
      'For doors and windows, enter the host wall element ID.',
      'Click "Create" to add the element to the Revit document.',
      'The system returns the new element ID on success.',
    ],
    stepsAr: [
      'افتح ريفيت → إنشاء من الشريط الجانبي.',
      'اختر تبويب نوع العنصر: جدار، أرضية، عمود، كمرة، باب، أو نافذة.',
      'أدخل الإحداثيات والمعلمات للعنصر.',
      'للأبواب والنوافذ، أدخل معرف عنصر الجدار المضيف.',
      'انقر "إنشاء" لإضافة العنصر إلى مستند ريفيت.',
      'يُرجع النظام معرف العنصر الجديد عند النجاح.',
    ],
    warningsEn: [
      'Revit must be connected before creating elements.',
      'Coordinates are in millimeters (internal Revit units).',
      'Wall type names must match types loaded in the Revit document.',
    ],
    warningsAr: [
      'يجب الاتصال بـ ريفيت قبل إنشاء العناصر.',
      'الإحداثيات بالمليمترات (وحدات ريفيت الداخلية).',
      'يجب أن تتطابق أسماء أنواع الجدران مع الأنواع المحملة في مستند ريفيت.',
    ],
    keywords: ['create', 'wall', 'floor', 'column', 'beam', 'door', 'window', 'إنشاء', 'جدار', 'أرضية', 'عمود', 'باب', 'نافذة'],
    relatedTopics: related.revit,
    navigateTo: '/revit/create',
    contextRoute: '/revit/create',
  },
  'revit.elements': {
    id: 'revit.elements',
    category: 'revit',
    titleEn: 'View Revit Elements',
    titleAr: 'عرض عناصر ريفيت',
    descriptionEn: 'Browse, search, filter, view, and delete elements in the connected Revit document.',
    descriptionAr: 'تصفح وابحث وفلتر واعرض واحذف العناصر في مستند ريفيت المتصل.',
    stepsEn: [
      'Open Revit → Elements from the sidebar.',
      'The element list loads automatically from the Revit API.',
      'Use the search bar to find elements by name or ID.',
      'Filter by category using the dropdown.',
      'Click the eye icon to view element details.',
      'Click the trash icon to delete an element.',
      'Click "Refresh" to reload the element list.',
    ],
    stepsAr: [
      'افتح ريفيت → عناصر من الشريط الجانبي.',
      'تُحمّل قائمة العناصر تلقائياً من Revit API.',
      'استخدم شريط البحث للعثور على عناصر بالاسم أو المعرف.',
      'فلترة بالفئة باستخدام القائمة المنسدلة.',
      'انقر أيقونة العين لعرض تفاصيل العنصر.',
      'انقر أيقونة سلة المهملات لحذف عنصر.',
      'انقر "تحديث" لإعادة تحميل قائمة العناصر.',
    ],
    warningsEn: [
      'Deleting elements is permanent in the Revit document.',
      'The element list reflects the current state of the Revit document.',
    ],
    warningsAr: [
      'حذف العناصر دائم في مستند ريفيت.',
      'تعكس قائمة العناصر الحالة الحالية لمستند ريفيت.',
    ],
    keywords: ['elements', 'list', 'search', 'filter', 'delete', 'عناصر', 'قائمة', 'بحث', 'فلترة', 'حذف'],
    relatedTopics: related.revit,
    navigateTo: '/revit/elements',
    contextRoute: '/revit/elements',
  },
  'revit.files': {
    id: 'revit.files',
    category: 'revit',
    titleEn: 'RVT File Management',
    titleAr: 'إدارة ملفات RVT',
    descriptionEn: 'Read, write, upload, and save RVT files through the Revit API.',
    descriptionAr: 'اقرأ واكتب وارفع واحفظ ملفات RVT عبر Revit API.',
    stepsEn: [
      'To read an RVT: enter the file path and click "Read".',
      'To upload: drag & drop a .rvt file or click to browse.',
      'To save: use the "Save" button on the Revit dashboard.',
      'The status card shows current document info.',
    ],
    stepsAr: [
      'لقراءة RVT: أدخل مسار الملف وانقر "قراءة".',
      'للرفع: اسحب وأفلت ملف .rvt أو انقر للتصفح.',
      'للحفظ: استخدم زر "حفظ" في لوحة تحكم ريفيت.',
      'تعرض بطاقة الحالة معلومات المستند الحالي.',
    ],
    warningsEn: [
      'RVT files can be very large (100MB+). Upload may take time.',
      'File paths must be accessible from the backend server.',
    ],
    warningsAr: [
      'قد تكون ملفات RVT كبيرة جداً (100MB+). قد يستغرق الرفع وقتاً.',
      'يجب أن تكون مسارات الملفات قابلة للوصول من خادم الخلفية.',
    ],
    keywords: ['rvt', 'file', 'read', 'write', 'upload', 'ملف', 'قراءة', 'كتابة', 'رفع'],
    relatedTopics: related.revit,
    navigateTo: '/revit',
    contextRoute: '/revit',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // DIGITAL TWIN
  // ═══════════════════════════════════════════════════════════════════════
  'digital-twin.overview': {
    id: 'digital-twin.overview',
    category: 'digital-twin',
    titleEn: 'Digital Twin Overview',
    titleAr: 'نظرة عامة على التوأم الرقمي',
    descriptionEn: 'The Digital Twin engine converts between AutoCAD (DWG) and Revit (RVT) formats bidirectionally.',
    descriptionAr: 'محرك التوأم الرقمي يحول بين صيغ أوتوكاد (DWG) وريفيت (RVT) في كلا الاتجاهين.',
    stepsEn: [
      'The Digital Twin page shows conversion status and configuration.',
      'Use the Convert sub-page to perform bidirectional conversions.',
      'Use the Config sub-page to edit conversion settings.',
      'Use the History sub-page to view past conversions and rollback.',
    ],
    stepsAr: [
      'تعرض صفحة التوأم الرقمي حالة التحويل والتكوين.',
      'استخدم صفحة التحويل الفرعية لإجراء تحويلات ثنائية الاتجاه.',
      'استخدم صفحة الإعدادات الفرعية لتحرير إعدادات التحويل.',
      'استخدم صفحة السجل الفرعية لعرض التحويلات السابقة والتراجع.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['digital-twin', 'convert', 'overview', 'توأم', 'رقمي', 'تحويل'],
    relatedTopics: related.digitalTwin,
    navigateTo: '/digital-twin',
    contextRoute: '/digital-twin',
  },
  'digital-twin.convert': {
    id: 'digital-twin.convert',
    category: 'digital-twin',
    titleEn: 'Convert Files',
    titleAr: 'تحويل الملفات',
    descriptionEn: 'Convert DWG ↔ RVT bidirectionally with element mapping and progress tracking.',
    descriptionAr: 'حوّل DWG ↔ RVT ثنائياً مع تعيين العناصر وتتبع التقدم.',
    stepsEn: [
      'Open Digital Twin → Convert from the sidebar.',
      'Enter the source file path.',
      'Select the target format: Revit (RVT), AutoCAD (DWG), or IFC.',
      'Click "Convert" to start the conversion.',
      'The progress bar shows conversion status.',
      'On success, the result shows element count and output file path.',
      'The conversion appears in the history timeline below.',
    ],
    stepsAr: [
      'افتح التوأم الرقمي → تحويل من الشريط الجانبي.',
      'أدخل مسار الملف المصدر.',
      'اختر الصيغة الهدف: ريفيت (RVT)، أوتوكاد (DWG)، أو IFC.',
      'انقر "تحويل" لبدء التحويل.',
      'يعرض شريط التقدم حالة التحويل.',
      'عند النجاح، تعرض النتيجة عدد العناصر ومسار ملف الإخراج.',
      'يظهر التحويل في الخط الزمني للسجل أدناه.',
    ],
    warningsEn: [
      'Large files may take several minutes to convert.',
      'Ensure sufficient disk space for output files.',
    ],
    warningsAr: [
      'قد تستغرق الملفات الكبيرة عدة دقائق للتحويل.',
      'تأكد من مساحة قرص كافية لملفات الإخراج.',
    ],
    keywords: ['convert', 'dwg', 'rvt', 'ifc', 'تحويل', 'صيغة'],
    relatedTopics: related.digitalTwin,
    navigateTo: '/digital-twin/convert',
    contextRoute: '/digital-twin/convert',
  },
  'digital-twin.config': {
    id: 'digital-twin.config',
    category: 'digital-twin',
    titleEn: 'Conversion Configuration',
    titleAr: 'إعدادات التحويل',
    descriptionEn: 'Edit the JSON configuration for the conversion engine and view available mappings.',
    descriptionAr: 'حرر تكوين JSON لمحرك التحويل واعرض التعيينات المتاحة.',
    stepsEn: [
      'Open Digital Twin → Config from the sidebar.',
      'The Config Editor shows the current JSON configuration.',
      'Edit the JSON directly in the text area.',
      'The editor validates JSON syntax in real-time.',
      'Click "Save Configuration" to apply changes.',
      'The Mappings section shows available element type mappings.',
    ],
    stepsAr: [
      'افتح التوأم الرقمي → إعدادات من الشريط الجانبي.',
      'يعرض محرر الإعدادات تكوين JSON الحالي.',
      'حرر JSON مباشرة في منطقة النص.',
      'يتحقق المحرر من صحة بناء JSON في الوقت الفعلي.',
      'انقر "حفظ الإعدادات" لتطبيق التغييرات.',
      'يعرض قسم التعيينات تعيينات أنواع العناصر المتاحة.',
    ],
    warningsEn: [
      'Invalid JSON cannot be saved — fix syntax errors first.',
      'Changing configuration may affect future conversions.',
    ],
    warningsAr: [
      'لا يمكن حفظ JSON غير صالح — أصلح أخطاء البناء أولاً.',
      'قد يؤثر تغيير الإعدادات على التحويلات المستقبلية.',
    ],
    keywords: ['config', 'json', 'mapping', 'settings', 'إعدادات', 'تكوين', 'تعيين'],
    relatedTopics: related.digitalTwin,
    navigateTo: '/digital-twin/config',
    contextRoute: '/digital-twin/config',
  },
  'digital-twin.history': {
    id: 'digital-twin.history',
    category: 'digital-twin',
    titleEn: 'Conversion History',
    titleAr: 'سجل التحويلات',
    descriptionEn: 'View past conversions and rollback to previous versions.',
    descriptionAr: 'اعرض التحويلات السابقة وتراجع إلى الإصدارات السابقة.',
    stepsEn: [
      'Open Digital Twin → History from the sidebar.',
      'The timeline shows all past conversions sorted by date.',
      'Each entry shows: source file, target file, conversion type, element count, and status.',
      'Click "Rollback" to revert to a previous version.',
      'The rollback restores the state at that conversion point.',
    ],
    stepsAr: [
      'افتح التوأم الرقمي → سجل من الشريط الجانبي.',
      'يعرض الخط الزمني جميع التحويلات السابقة مرتبة بالتاريخ.',
      'يعرض كل إدخال: الملف المصدر، الملف الهدف، نوع التحويل، عدد العناصر، والحالة.',
      'انقر "تراجع" للرجوع إلى إصدار سابق.',
      'يستعيد التراجع الحالة عند نقطة التحويل تلك.',
    ],
    warningsEn: [
      'Rollback overwrites the current state — proceed with caution.',
      'Once rolled back, newer conversions are not automatically removed.',
    ],
    warningsAr: [
      'الكتابة فوق الحالة الحالية عند التراجع — تابع بحذر.',
      'بمجرد التراجع، لا تُزال التحويلات الأحدث تلقائياً.',
    ],
    keywords: ['history', 'timeline', 'rollback', 'version', 'سجل', 'خط زمني', 'تراجع', 'إصدار'],
    relatedTopics: related.digitalTwin,
    navigateTo: '/digital-twin/history',
    contextRoute: '/digital-twin/history',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // REPORTS
  // ═══════════════════════════════════════════════════════════════════════
  'reports.generate': {
    id: 'reports.generate',
    category: 'reports',
    titleEn: 'Generate Reports',
    titleAr: 'توليد التقارير',
    descriptionEn: 'Generate NFPA 72 compliance reports, battery calculations, and coverage analysis.',
    descriptionAr: 'ولّد تقارير امتثال NFPA 72 وحسابات البطارية وتحليل التغطية.',
    stepsEn: [
      'Open Reports from the sidebar.',
      'Select the report type (comprehensive, battery, coverage, etc.).',
      'Configure execution parameters (coverage level, deterministic analysis, etc.).',
      'Click "Generate" to create the report.',
      'View the report in the list once generated.',
      'Download reports in various formats (PDF, DXF, IFC).',
    ],
    stepsAr: [
      'افتح التقارير من الشريط الجانبي.',
      'اختر نوع التقرير (شامل، بطارية، تغطية، إلخ).',
      'تكوين معلمات التنفيذ (مستوى التغطية، التحليل الحتمي، إلخ).',
      'انقر "توليد" لإنشاء التقرير.',
      'اعرض التقرير في القائمة بمجرد توليده.',
      'حمّل التقارير بصيغ مختلفة (PDF, DXF, IFC).',
    ],
    warningsEn: [
      'Report generation may take time for large projects.',
      'Ensure the backend is connected before generating reports.',
    ],
    warningsAr: [
      'قد يستغرق توليد التقرير وقتاً للمشاريع الكبيرة.',
      'تأكد من اتصال الخادم الخلفي قبل توليد التقارير.',
    ],
    keywords: ['report', 'generate', 'pdf', 'compliance', 'تقرير', 'توليد', 'امتثال'],
    relatedTopics: related.reports,
    navigateTo: '/reports',
    contextRoute: '/reports',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // ELEMENTS
  // ═══════════════════════════════════════════════════════════════════════
  'elements.overview': {
    id: 'elements.overview',
    category: 'elements',
    titleEn: 'Elements Overview',
    titleAr: 'نظرة عامة على العناصر',
    descriptionEn: 'View, create, edit, and delete BIM elements in the universal data model.',
    descriptionAr: 'عرض وإنشاء وتحرير وحذف عناصر BIM في النموذج الموحد للبيانات.',
    stepsEn: [
      'Open Elements from the sidebar.',
      'The list shows all elements in the current project.',
      'Use the search and filter to find specific elements.',
      'Click "New Element" to create a new element.',
      'Click on an element to view or edit its details.',
      'Delete elements using the delete button.',
    ],
    stepsAr: [
      'افتح العناصر من الشريط الجانبي.',
      'تعرض القائمة جميع العناصر في المشروع الحالي.',
      'استخدم البحث والفلترة للعثور على عناصر محددة.',
      'انقر "عنصر جديد" لإنشاء عنصر جديد.',
      'انقر على عنصر لعرض أو تحرير تفاصيله.',
      'احذف العناصر باستخدام زر الحذف.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['elements', 'bim', 'udm', 'عناصر', 'نموذج'],
    relatedTopics: related.elements,
    navigateTo: '/elements',
    contextRoute: '/elements',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CONNECTIONS
  // ═══════════════════════════════════════════════════════════════════════
  'connections.create': {
    id: 'connections.create',
    category: 'connections',
    titleEn: 'Create Connections',
    titleAr: 'إنشاء التوصيلات',
    descriptionEn: 'Create logical connections between elements (e.g. panel → device wiring).',
    descriptionAr: 'أنشئ توصيلات منطقية بين العناصر (مثل: لوحة → أسلاك جهاز).',
    stepsEn: [
      'Open Connections from the sidebar.',
      'Click "New Connection" to create a connection.',
      'Select the source and target elements.',
      'Specify the connection type (wired, wireless, SLC, NAC).',
      'Click "Create" to save the connection.',
    ],
    stepsAr: [
      'افتح التوصيلات من الشريط الجانبي.',
      'انقر "توصيل جديد" لإنشاء توصيل.',
      'اختر العناصر المصدر والهدف.',
      'حدد نوع التوصيل (سلكي، لاسلكي، SLC، NAC).',
      'انقر "إنشاء" لحفظ التوصيل.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['connection', 'wire', 'slc', 'nac', 'توصيل', 'سلك', 'ربط'],
    relatedTopics: related.connections,
    navigateTo: '/connections',
    contextRoute: '/connections',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // CONFLICTS
  // ═══════════════════════════════════════════════════════════════════════
  'conflicts.overview': {
    id: 'conflicts.overview',
    category: 'conflicts',
    titleEn: 'Conflicts Overview',
    titleAr: 'نظرة عامة على التعارضات',
    descriptionEn: 'Detect and resolve conflicts between BIM elements from different disciplines.',
    descriptionAr: 'اكتشف وحل التعارضات بين عناصر BIM من تخصصات مختلفة.',
    stepsEn: [
      'Open Conflicts from the sidebar.',
      'Click "Detect Conflicts" to scan for clashes.',
      'Review the list of detected conflicts.',
      'Click "Resolve" on a conflict to choose a resolution strategy.',
      'Resolved conflicts are marked as resolved.',
    ],
    stepsAr: [
      'افتح التعارضات من الشريط الجانبي.',
      'انقر "اكتشاف التعارضات" للبحث عن التضاربات.',
      'راجع قائمة التعارضات المكتشفة.',
      'انقر "حل" على تعارض لاختيار استراتيجية الحل.',
      'تُعلّم التعارضات المحلولة كمحلولة.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['conflict', 'clash', 'resolve', 'detect', 'تعارض', 'تضارب', 'حل', 'اكتشاف'],
    relatedTopics: related.conflicts,
    navigateTo: '/conflicts',
    contextRoute: '/conflicts',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // SETTINGS
  // ═══════════════════════════════════════════════════════════════════════
  'settings.backend': {
    id: 'settings.backend',
    category: 'settings',
    titleEn: 'Backend Settings',
    titleAr: 'إعدادات الخادم الخلفي',
    descriptionEn: 'Configure backend connection, API timeout, retry attempts, and system preferences.',
    descriptionAr: 'تكوين اتصال الخادم الخلفي، مهلة API، محاولات الإعادة، وتفضيلات النظام.',
    stepsEn: [
      'Open Settings from the sidebar.',
      'General tab: configure theme, language, notifications.',
      'Security tab: configure password expiry, 2FA.',
      'API tab: set API timeout and retry attempts.',
      'Reports tab: configure report defaults.',
      'Click "Save" in each tab to apply changes.',
    ],
    stepsAr: [
      'افتح الإعدادات من الشريط الجانبي.',
      'تبويب عام: تكوين السمة، اللغة، الإشعارات.',
      'تبويب الأمان: تكوين انتهاء كلمة المرور، المصادقة الثنائية.',
      'تبويب API: ضبط مهلة API ومحاولات الإعادة.',
      'تبويب التقارير: تكوين افتراضات التقرير.',
      'انقر "حفظ" في كل تبويب لتطبيق التغييرات.',
    ],
    warningsEn: [
      'Changes to API settings may require a page refresh to take effect.',
    ],
    warningsAr: [
      'قد تتطلب تغييرات إعدادات API تحديث الصفحة لتسري مفعولها.',
    ],
    keywords: ['settings', 'backend', 'api', 'timeout', 'إعدادات', 'خادم', 'مهلة'],
    relatedTopics: related.settings,
    navigateTo: '/settings',
    contextRoute: '/settings',
  },
  'settings.api-keys': {
    id: 'settings.api-keys',
    category: 'settings',
    titleEn: 'API Key Management',
    titleAr: 'إدارة مفاتيح API',
    descriptionEn: 'Create, view, update, and delete API keys with different roles (admin, engineer, viewer).',
    descriptionAr: 'إنشاء وعرض وتحديث وحذف مفاتيح API بأدوار مختلفة (مدير، مهندس، عارض).',
    stepsEn: [
      'API keys are managed via the /admin/keys backend endpoint.',
      'Each key has a role: ADMIN (full access), ENGINEER (read/write), VIEWER (read-only).',
      'Set your API key in the Settings → Security tab or via VITE_FIREAI_API_KEY env var.',
      'Keys can be revoked by administrators at any time.',
    ],
    stepsAr: [
      'تُدار مفاتيح API عبر نقطة نهاية /admin/keys الخلفية.',
      'لكل مفتاح دور: ADMIN (وصول كامل)، ENGINEER (قراءة/كتابة)، VIEWER (قراءة فقط).',
      'اضبط مفتاح API في الإعدادات → تبويب الأمان أو عبر متغير البيئة VITE_FIREAI_API_KEY.',
      'يمكن للمديرين إلغاء المفاتيح في أي وقت.',
    ],
    warningsEn: [
      'Never share your API key publicly.',
      'Rotate keys regularly for security.',
    ],
    warningsAr: [
      'لا تشارك مفتاح API علناً أبداً.',
      'بدّل المفاتيح بانتظام للأمان.',
    ],
    keywords: ['api', 'key', 'admin', 'role', 'مفتاح', 'دور', 'مدير'],
    relatedTopics: related.settings,
    navigateTo: '/settings',
    contextRoute: '/settings',
  },

  // ═══════════════════════════════════════════════════════════════════════
  // TROUBLESHOOTING
  // ═══════════════════════════════════════════════════════════════════════
  'troubleshooting.backend': {
    id: 'troubleshooting.backend',
    category: 'troubleshooting',
    titleEn: 'Backend Connection Issues',
    titleAr: 'مشاكل اتصال الخادم الخلفي',
    descriptionEn: 'Resolve common backend connection problems.',
    descriptionAr: 'حل مشاكل اتصال الخادم الخلفي الشائعة.',
    stepsEn: [
      'Check that the backend is running: visit http://localhost:8000/docs',
      'Verify the backend URL in Settings → API.',
      'Check browser console for CORS errors.',
      'Ensure your API key is valid and not expired.',
      'Restart the backend: python -m uvicorn backend.app:app --reload',
    ],
    stepsAr: [
      'تحقق من أن الخادم الخلفي يعمل: زر http://localhost:8000/docs',
      'تحقق من عنوان الخادم الخلفي في الإعدادات → API.',
      'افحص وحدة التحكم في المتصفح لأخطاء CORS.',
      'تأكد من أن مفتاح API صالح وغير منتهي.',
      'أعد تشغيل الخادم الخلفي: python -m uvicorn backend.app:app --reload',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['troubleshoot', 'backend', 'connection', 'cors', 'استكشاف', 'خادم', 'اتصال'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.api': {
    id: 'troubleshooting.api',
    category: 'troubleshooting',
    titleEn: 'API Errors (401, 403, 404, 500)',
    titleAr: 'أخطاء API (401، 403، 404، 500)',
    descriptionEn: 'Diagnose and fix common API error codes.',
    descriptionAr: 'شخّص وأصلح أكواد أخطاء API الشائعة.',
    stepsEn: [
      '401 Unauthorized: API key is missing or invalid. Set it in Settings → Security.',
      '403 Forbidden: Your role lacks the required permission. Contact an admin.',
      '404 Not Found: The endpoint URL may have changed. Check /docs for current routes.',
      '500 Internal Server Error: Check backend logs. May be a bug — report it.',
      '503 Service Unavailable: Backend is starting up or overloaded. Retry.',
    ],
    stepsAr: [
      '401 غير مصرح: مفتاح API مفقود أو غير صالح. اضبطه في الإعدادات → الأمان.',
      '403 محظور: دورك يفتقر إلى الإذن المطلوب. اتصل بمدير.',
      '404 غير موجود: قد يكون عنوان URL قد تغير. تحقق من /docs للمسارات الحالية.',
      '500 خطأ داخلي: افحص سجلات الخادم الخلفي. قد يكون خطأ — أبلغ عنه.',
      '503 خدمة غير متاحة: الخادم الخلفي يبدأ أو محمل. أعد المحاولة.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['error', '401', '403', '404', '500', 'خطأ', 'استكشاف'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.auth': {
    id: 'troubleshooting.auth',
    category: 'troubleshooting',
    titleEn: 'Authentication Problems',
    titleAr: 'مشاكل المصادقة',
    descriptionEn: 'Fix API key and authentication issues.',
    descriptionAr: 'أصلح مشاكل مفتاح API والمصادقة.',
    stepsEn: [
      'Ensure your API key is entered in Settings → Security.',
      'The key is case-sensitive — copy it exactly.',
      'Session storage clears when the tab closes — re-enter if needed.',
      'If the key is expired, contact an administrator to generate a new one.',
    ],
    stepsAr: [
      'تأكد من إدخال مفتاح API في الإعدادات → الأمان.',
      'المفتاح حساس لحالة الأحرف — انسخه بالضبط.',
      'يُمسح التخزين المؤقت عند إغلاق التبويب — أعد الإدخال عند الحاجة.',
      'إذا انتهت صلاحية المفتاح، اتصل بمدير لتوليد مفتاح جديد.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['auth', 'api', 'key', 'session', 'مصادقة', 'مفتاح', 'جلسة'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.app-crash': {
    id: 'troubleshooting.app-crash',
    category: 'troubleshooting',
    titleEn: 'Application Crash or Freeze',
    titleAr: 'تعطل أو تجمد التطبيق',
    descriptionEn: 'Recover from application crashes and freezes.',
    descriptionAr: 'التعافي من تعطل أو تجمد التطبيق.',
    stepsEn: [
      'Hard refresh: Ctrl+Shift+R (or Cmd+Shift+R on Mac).',
      'Clear browser cache and sessionStorage.',
      'Check browser console (F12) for JavaScript errors.',
      'Restart the backend server.',
      'If the issue persists, report the error with console output.',
    ],
    stepsAr: [
      'تحديث قاسي: Ctrl+Shift+R (أو Cmd+Shift+R على Mac).',
      'امسح ذاكرة التخزين المؤقت للمتصفح و sessionStorage.',
      'افحص وحدة التحكم (F12) لأخطاء JavaScript.',
      'أعد تشغيل خادم الخلفية.',
      'إذا استمرت المشكلة، أبلغ عن الخطأ مع مخرجات وحدة التحكم.',
    ],
    warningsEn: [],
    warningsAr: [],
    keywords: ['crash', 'freeze', 'refresh', 'تعطل', 'تجمد', 'تحديث'],
    relatedTopics: related.troubleshooting,
  },
};

// ─── Legacy exports for backward compatibility ─────────────────────────────

export const HELP_TOPIC_ORDER: HelpTopicId[] = Object.keys(HELP_TOPICS) as HelpTopicId[];

export const HELP_CATEGORY_LABELS: Record<string, { en: string; ar: string }> = {
  'getting-started': { en: 'Getting Started', ar: 'البدء السريع' },
  'dashboard': { en: 'Dashboard', ar: 'لوحة التحكم' },
  'projects': { en: 'Projects', ar: 'المشاريع' },
  'engineering': { en: 'Engineering', ar: 'الهندسة' },
  'fire-alarm': { en: 'Fire Alarm', ar: 'إنذار الحريق' },
  'autocad': { en: 'AutoCAD', ar: 'أوتوكاد' },
  'revit': { en: 'Revit', ar: 'ريفيت' },
  'digital-twin': { en: 'Digital Twin', ar: 'التوأم الرقمي' },
  'reports': { en: 'Reports', ar: 'التقارير' },
  'elements': { en: 'Elements', ar: 'العناصر' },
  'connections': { en: 'Connections', ar: 'التوصيلات' },
  'conflicts': { en: 'Conflicts', ar: 'التعارضات' },
  'settings': { en: 'Settings', ar: 'الإعدادات' },
  'troubleshooting': { en: 'Troubleshooting', ar: 'استكشاف الأخطاء' },
  'general': { en: 'General', ar: 'عام' },
};
