import type { HelpCategory, HelpTopic, HelpTopicId } from './types';

const related = {
  dashboard: ['projects.create', 'reports.generate', 'settings.backend'] as HelpTopicId[],
  projects: ['projects.create', 'projects.manage', 'connections.create', 'reports.generate'] as HelpTopicId[],
  engineering: ['engineering.overview', 'reports.generate', 'fire-alarm.detector-placement'] as HelpTopicId[],
  fireAlarm: ['fire-alarm.detector-placement', 'fire-alarm.symbol-library', 'fire-alarm.zone-navigation', 'reports.generate'] as HelpTopicId[],
  reports: ['reports.generate', 'troubleshooting.api', 'troubleshooting.backend'] as HelpTopicId[],
  digitalTwin: ['digital-twin.overview', 'elements.overview', 'connections.create', 'conflicts.overview'] as HelpTopicId[],
  elements: ['elements.overview', 'connections.create', 'conflicts.overview'] as HelpTopicId[],
  connections: ['connections.create', 'elements.overview', 'conflicts.overview'] as HelpTopicId[],
  conflicts: ['conflicts.overview', 'elements.overview', 'connections.create'] as HelpTopicId[],
  settings: ['settings.backend', 'troubleshooting.backend', 'troubleshooting.api', 'troubleshooting.auth'] as HelpTopicId[],
  troubleshooting: ['troubleshooting.backend', 'troubleshooting.api', 'troubleshooting.auth', 'troubleshooting.app-crash'] as HelpTopicId[],
};

export const HELP_TOPICS: Record<HelpTopicId, HelpTopic> = {
  'dashboard.overview': {
    id: 'dashboard.overview',
    category: 'dashboard',
    titleEn: 'Dashboard overview',
    titleAr: 'نظرة عامة على لوحة التحكم',
    descriptionEn: 'Use the dashboard to review project counts, device totals, and backend health before starting engineering work.',
    descriptionAr: 'استخدم لوحة التحكم لمراجعة عدد المشاريع وإجمالي الأجهزة وحالة الخادم الخلفي قبل بدء العمل الهندسي.',
    stepsEn: [
      'Open the dashboard from the sidebar.',
      'Check the backend status badge in the top bar.',
      'Review active projects, device counts, and system health cards.',
      'Use the refresh action to re-run the health and project checks.',
    ],
    stepsAr: [
      'افتح لوحة التحكم من الشريط الجانبي.',
      'تحقق من شارة حالة الخادم الخلفي في الشريط العلوي.',
      'راجع بطاقات المشاريع النشطة وإجمالي الأجهزة وصحة النظام.',
      'استخدم زر التحديث لإعادة فحص الحالة والمشاريع.',
    ],
    warningsEn: [
      'Dashboard counters are only as current as the last successful API call.',
      'If the backend is disconnected, project and device data may be stale.',
    ],
    warningsAr: [
      'تعتمد عدادات لوحة التحكم على آخر استدعاء API ناجح.',
      'إذا كان الخادم الخلفي غير متصل فقد تكون بيانات المشاريع والأجهزة قديمة.',
    ],
    keywords: ['dashboard', 'overview', 'health', 'status', 'projects', 'devices', 'backend', 'لوحة', 'حالة', 'مشاريع'],
    relatedTopics: related.dashboard,
    navigateTo: '/dashboard',
  },
  'projects.create': {
    id: 'projects.create',
    category: 'projects',
    titleEn: 'Create a project',
    titleAr: 'إنشاء مشروع',
    descriptionEn: 'Create a new fire alarm digital twin project with a name, description, and author context.',
    descriptionAr: 'أنشئ مشروع توأم رقمي جديد لأنظمة الإنذار بالاسم والوصف ومعلومات المؤلف.',
    stepsEn: [
      'Open Projects from the sidebar.',
      'Select New Project.',
      'Enter a clear project name and optional description.',
      'Select Create Project and wait for the API response.',
    ],
    stepsAr: [
      'افتح صفحة المشاريع من الشريط الجانبي.',
      'اختر مشروع جديد.',
      'أدخل اسم مشروع واضح ووصفًا اختياريًا.',
      'اختر إنشاء مشروع وانتظر استجابة API.',
    ],
    warningsEn: [
      'Project names should be unique and descriptive for audit traceability.',
      'If creation fails, check backend health and network connectivity.',
    ],
    warningsAr: [
      'ينبغي أن تكون أسماء المشاريع فريدة وواضحة لتتبع التدقيق.',
      'إذا فشل الإنشاء فتحقق من صحة الخادم الخلفي واتصال الشبكة.',
    ],
    keywords: ['project', 'create', 'new', 'fire alarm', 'digital twin', 'مشروع', 'إنشاء', 'جديد'],
    relatedTopics: ['projects.manage', 'settings.backend', 'troubleshooting.backend'],
    navigateTo: '/projects',
  },
  'projects.manage': {
    id: 'projects.manage',
    category: 'projects',
    titleEn: 'Manage projects',
    titleAr: 'إدارة المشاريع',
    descriptionEn: 'Filter, view, sync, and delete projects while preserving traceable engineering context.',
    descriptionAr: 'صفِّ المشاريع واعرضها وزامنّها واحذفها مع الحفاظ على السياق الهندسي القابل للتتبع.',
    stepsEn: [
      'Use status filters to focus on active, draft, archived, or inactive projects.',
      'Open a project to inspect devices, connections, and reports.',
      'Use Sync when the backend should refresh derived data.',
      'Delete only projects that are no longer needed; deletion cannot be undone.',
    ],
    stepsAr: [
      'استخدم مصفيات الحالة للتركيز على المشاريع النشطة أو المسودات أو المؤرشفة أو غير النشطة.',
      'افتح مشروعًا لفحص الأجهزة والاتصالات والتقارير.',
      'استخدم المزامنة عندما يحتاج الخادم الخلفي إلى تحديث البيانات المشتقة.',
      'احذف فقط المشاريع التي لم تعد مطلوبة؛ لا يمكن التراجع عن الحذف.',
    ],
    warningsEn: [
      'Deleting a project may remove associated devices, connections, and reports.',
      'Syncing large projects can take longer depending on backend load.',
    ],
    warningsAr: [
      'قد يؤدي حذف المشروع إلى إزالة الأجهزة والاتصالات والتقارير المرتبطة به.',
      'قد تستغرق مزامنة المشاريع الكبيرة وقتًا أطول حسب حمل الخادم الخلفي.',
    ],
    keywords: ['projects', 'manage', 'filter', 'sync', 'delete', 'archive', 'مشاريع', 'إدارة', 'مزامنة', 'حذف'],
    relatedTopics: ['projects.create', 'connections.create', 'reports.generate'],
    navigateTo: '/projects',
  },
  'engineering.overview': {
    id: 'engineering.overview',
    category: 'engineering',
    titleEn: 'Engineering calculations',
    titleAr: 'الحسابات الهندسية',
    descriptionEn: 'Run voltage drop, cable sizing, and battery calculations for fire alarm circuits.',
    descriptionAr: 'شغّل حسابات هبوط الجهد وتحديد حجم الكابل وحسابات البطارية لدوائر الإنذار.',
    stepsEn: [
      'Open Engineering from the sidebar.',
      'Choose voltage drop, cable sizing, or battery calculation.',
      'Enter circuit values using consistent units.',
      'Review the result badge and recommendations before applying changes.',
    ],
    stepsAr: [
      'افتح الحسابات الهندسية من الشريط الجانبي.',
      'اختر هبوط الجهد أو تحديد حجم الكابل أو حساب البطارية.',
      'أدخل قيم الدائرة باستخدام وحدات متسقة.',
      'راجع شارة النتيجة والتوصيات قبل تطبيق أي تغييرات.',
    ],
    warningsEn: [
      'Calculations are engineering aids and should be validated against applicable codes and site data.',
      'Use conservative assumptions when source data is incomplete.',
    ],
    warningsAr: [
      'تُعد الحسابات أدوات هندسية مساعدة ويجب التحقق منها وفق الأكواد المعمول بها وبيانات الموقع.',
      'استخدم افتراضات محافظة عندما تكون بيانات المصدر غير مكتملة.',
    ],
    keywords: ['engineering', 'voltage', 'cable', 'battery', 'calculation', 'NFPA', 'هندسة', 'جهد', 'كابل', 'بطارية'],
    relatedTopics: related.engineering,
    navigateTo: '/engineering',
  },
  'fire-alarm.detector-placement': {
    id: 'fire-alarm.detector-placement',
    category: 'fire-alarm',
    titleEn: 'Detector placement',
    titleAr: 'وضع الكواشف',
    descriptionEn: 'Place smoke, heat, pull station, horn/strobe, and panel devices on the fire alarm designer canvas.',
    descriptionAr: 'ضع كواشف الدخان والحرارة ومحطات السحب وأجهزة الإنذار واللوحة على لوحة مصمم الإنذار.',
    stepsEn: [
      'Open Fire Alarm Designer.',
      'Choose a device type from the toolbar.',
      'Place the device on the canvas and align it with the floor plan grid.',
      'Select the device to review properties such as zone, address, and coverage.',
    ],
    stepsAr: [
      'افتح مصمم أنظمة الإنذار.',
      'اختر نوع الجهاز من شريط الأدوات.',
      'ضع الجهاز على اللوحة وحاذه مع شبكة مخطط الطابق.',
      'حدد الجهاز لمراجعة خصائصه مثل المنطقة والعنوان والتغطية.',
    ],
    warningsEn: [
      'Detector spacing must be verified against NFPA 72 and the approved project basis.',
      'Do not rely on visual placement alone for code compliance.',
    ],
    warningsAr: [
      'يجب التحقق من تباعد الكواشف وفق NFPA 72 والأساس المعتمد للمشروع.',
      'لا تعتمد على الوضع المرئي وحده للامتثال للكود.',
    ],
    keywords: ['fire alarm', 'detector', 'smoke', 'heat', 'placement', 'coverage', 'NFPA', 'كاشف', 'دخان', 'حرارة', 'تغطية'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm/designer',
  },
  'fire-alarm.symbol-library': {
    id: 'fire-alarm.symbol-library',
    category: 'fire-alarm',
    titleEn: 'Fire alarm symbol library',
    titleAr: 'مكتبة رموز الإنذار',
    descriptionEn: 'Use the symbol library to select standard fire alarm device symbols consistently.',
    descriptionAr: 'استخدم مكتبة الرموز لاختيار رموز أجهزة الإنذار القياسية بشكل متسق.',
    stepsEn: [
      'Open the symbol library in the designer.',
      'Select the required device symbol.',
      'Confirm the symbol matches the project legend and AHJ requirements.',
      'Use the same symbol family across sheets and exports.',
    ],
    stepsAr: [
      'افتح مكتبة الرموز في المصمم.',
      'اختر رمز الجهاز المطلوب.',
      'تأكد من مطابقة الرمز لجدول رموز المشروع ومتطلبات الجهة المختصة.',
      'استخدم عائلة الرموز نفسها عبر المخططات والتصدير.',
    ],
    warningsEn: [
      'Symbol appearance does not replace device engineering properties.',
      'Custom symbols should be reviewed before export or submission.',
    ],
    warningsAr: [
      'مظهر الرمز لا يغني عن خصائص الجهاز الهندسية.',
      'ينبغي مراجعة الرموز المخصصة قبل التصدير أو التقديم.',
    ],
    keywords: ['symbol', 'library', 'fire alarm', 'legend', 'NFPA', 'device', 'رمز', 'مكتبة', 'إنذار', 'جدول'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm/designer',
  },
  'fire-alarm.zone-navigation': {
    id: 'fire-alarm.zone-navigation',
    category: 'fire-alarm',
    titleEn: 'Zone navigation',
    titleAr: 'التنقل بين المناطق',
    descriptionEn: 'Navigate the fire alarm system tree by panel, loop, circuit, and zone.',
    descriptionAr: 'تنقل في شجرة نظام الإنذار حسب اللوحة والحلقة والدائرة والمنطقة.',
    stepsEn: [
      'Open the system navigator panel.',
      'Expand panels, loops, circuits, and zones.',
      'Select a device to highlight its location and properties.',
      'Use zoom actions to focus on a specific zone.',
    ],
    stepsAr: [
      'افتح لوحة ملاحة النظام.',
      'وسّع اللوحات والحلقات والدوائر والمناطق.',
      'حدد جهازًا لإبراز موقعه وخصائصه.',
      'استخدم إجراءات التكبير للتركيز على منطقة محددة.',
    ],
    warningsEn: [
      'Zone IDs should match the approved cause-and-effect and addressing plan.',
      'Verify selected devices before changing zone assignments.',
    ],
    warningsAr: [
      'ينبغي أن تتطابق معرفات المناطق مع خطة السبب والنتيجة والعنونة المعتمدة.',
      'تحقق من الأجهزة المحددة قبل تغيير تعيينات المناطق.',
    ],
    keywords: ['zone', 'navigator', 'panel', 'loop', 'circuit', 'fire alarm', 'منطقة', 'ملاحة', 'لوحة', 'حلقة'],
    relatedTopics: related.fireAlarm,
    navigateTo: '/fire-alarm',
  },
  'reports.generate': {
    id: 'reports.generate',
    category: 'reports',
    titleEn: 'Generate reports',
    titleAr: 'إنشاء التقارير',
    descriptionEn: 'Generate deterministic fire alarm engineering reports such as coverage, battery, voltage drop, and compliance reports.',
    descriptionAr: 'أنشئ تقارير هندسية حتمية لأنظمة الإنذار مثل التغطية والبطارية وهبوط الجهد والامتثال.',
    stepsEn: [
      'Open Reports and select the target project.',
      'Choose the report type and execution parameters.',
      'Enable NFPA compliance checks when required.',
      'Generate the report and review warnings before export.',
    ],
    stepsAr: [
      'افتح التقارير واختر المشروع المستهدف.',
      'اختر نوع التقرير ومعلمات التنفيذ.',
      'فعّل فحوصات الامتثال لـ NFPA عند الحاجة.',
      'أنشئ التقرير وراجع التحذيرات قبل التصدير.',
    ],
    warningsEn: [
      'Report results depend on current project data and backend calculation services.',
      'Do not submit reports with unresolved warnings or stale backend data.',
    ],
    warningsAr: [
      'تعتمد نتائج التقارير على بيانات المشروع الحالية وخدمات حساب الخادم الخلفي.',
      'لا تقدم تقارير تحتوي على تحذيرات غير محلولة أو بيانات قديمة.',
    ],
    keywords: ['report', 'generate', 'coverage', 'battery', 'voltage', 'compliance', 'export', 'تقرير', 'إنشاء', 'تغطية', 'بطارية'],
    relatedTopics: related.reports,
    navigateTo: '/reports',
  },
  'digital-twin.overview': {
    id: 'digital-twin.overview',
    category: 'digital-twin',
    titleEn: 'Digital twin conversion workflow',
    titleAr: 'سير عمل تحويل التوأم الرقمي',
    descriptionEn: 'Convert between AutoCAD and Revit models while preserving semantic mapping, units, and version history.',
    descriptionAr: 'حوّل بين نماذج AutoCAD و Revit مع الحفاظ على الربط الدلالي والوحدات وسجل الإصدارات.',
    stepsEn: [
      'Open Digital Twin from the sidebar.',
      'Upload a DWG, DXF, or RVT file.',
      'Confirm conversion direction and unit settings.',
      'Run conversion and inspect warnings before saving version history.',
    ],
    stepsAr: [
      'افتح التوأم الرقمي من الشريط الجانبي.',
      'ارفع ملف DWG أو DXF أو RVT.',
      'أكد اتجاه التحويل وإعدادات الوحدات.',
      'شغّل التحويل وافحص التحذيرات قبل حفظ سجل الإصدارات.',
    ],
    warningsEn: [
      'Review mapping results before using converted geometry in engineering deliverables.',
      'Keep source files until the converted model is validated.',
    ],
    warningsAr: [
      'راجع نتائج الربط قبل استخدام الهندسة المحولة في مخرجات هندسية.',
      'احتفظ بالملفات المصدرية حتى يتم التحقق من النموذج المحول.',
    ],
    keywords: ['digital twin', 'autocad', 'revit', 'conversion', 'mapping', 'version', 'توأم رقمي', 'أوتوكاد', 'ريفيت', 'تحويل'],
    relatedTopics: related.digitalTwin,
    navigateTo: '/digital-twin',
  },
  'elements.overview': {
    id: 'elements.overview',
    category: 'elements',
    titleEn: 'Elements overview',
    titleAr: 'نظرة عامة على العناصر',
    descriptionEn: 'Review BIM elements, properties, geometry, versions, and linked relationships.',
    descriptionAr: 'راجع عناصر BIM وخصائصها وهندستها وإصداراتها والعلاقات المرتبطة بها.',
    stepsEn: [
      'Open Elements from the sidebar.',
      'Filter by element type when the list is large.',
      'Open an element to inspect geometry, properties, and connections.',
      'Create or update elements only after confirming source model ownership.',
    ],
    stepsAr: [
      'افتح العناصر من الشريط الجانبي.',
      'صفِّ حسب نوع العنصر عندما تكون القائمة كبيرة.',
      'افتح عنصرًا لفحص الهندسة والخصائص والاتصالات.',
      'أنشئ أو حدّث العناصر فقط بعد تأكيد ملكية النموذج المصدر.',
    ],
    warningsEn: [
      'Element edits can affect downstream clash detection and report generation.',
      'Verify geometry units before creating elements manually.',
    ],
    warningsAr: [
      'قد تؤثر تعديلات العناصر على كشف التعارضات وإنشاء التقارير لاحقًا.',
      'تحقق من وحدات الهندسة قبل إنشاء العناصر يدويًا.',
    ],
    keywords: ['elements', 'BIM', 'geometry', 'properties', 'version', 'Revit', 'عناصر', 'نموذج', 'خصائص', 'هندسة'],
    relatedTopics: related.elements,
    navigateTo: '/elements',
  },
  'connections.create': {
    id: 'connections.create',
    category: 'connections',
    titleEn: 'Create connections',
    titleAr: 'إنشاء الاتصالات',
    descriptionEn: 'Create parametric or non-parametric relationships between BIM elements.',
    descriptionAr: 'أنشئ علاقات معلمية أو غير معلمية بين عناصر BIM.',
    stepsEn: [
      'Open Connections from the sidebar.',
      'Select Create Connection.',
      'Enter source and target element IDs.',
      'Choose a relationship type and mark it as parametric when appropriate.',
    ],
    stepsAr: [
      'افتح الاتصالات من الشريط الجانبي.',
      'اختر إنشاء اتصال.',
      'أدخل معرف العنصر المصدر والهدف.',
      'اختر نوع العلاقة وعلّمها كمعلمية عند الحاجة.',
    ],
    warningsEn: [
      'Invalid element IDs will fail validation.',
      'Parametric relationships should be used only when downstream geometry depends on the relationship.',
    ],
    warningsAr: [
      'ستفشل المعرفات غير الصالحة أثناء التحقق.',
      'ينبغي استخدام العلاقات المعلمية فقط عندما تعتمد الهندسة اللاحقة على العلاقة.',
    ],
    keywords: ['connection', 'create', 'parametric', 'element', 'relationship', 'BIM', 'اتصال', 'إنشاء', 'معلمي', 'علاقة'],
    relatedTopics: related.connections,
    navigateTo: '/connections',
  },
  'conflicts.overview': {
    id: 'conflicts.overview',
    category: 'conflicts',
    titleEn: 'Conflicts overview',
    titleAr: 'نظرة عامة على التعارضات',
    descriptionEn: 'Detect, review, and resolve conflicts between data sources or model versions.',
    descriptionAr: 'اكشف التعارضات وراجعها وحلّها بين مصادر البيانات أو إصدارات النموذج.',
    stepsEn: [
      'Open Conflicts from the sidebar.',
      'Run conflict detection when source data changes.',
      'Review unresolved conflicts by element and source.',
      'Choose last-write-wins or semantic merge based on engineering impact.',
    ],
    stepsAr: [
      'افتح التعارضات من الشريط الجانبي.',
      'شغّل كشف التعارضات عند تغير بيانات المصدر.',
      'راجع التعارضات غير المحلولة حسب العنصر والمصدر.',
      'اختر آخر كتابة تفوز أو الدمج الدلالي حسب الأثر الهندسي.',
    ],
    warningsEn: [
      'Resolving a conflict can overwrite another source of truth.',
      'Prefer semantic merge when both sources contain valid engineering intent.',
    ],
    warningsAr: [
      'حل التعارض قد يستبدل مصدر حقيقة آخر.',
      'فضّل الدمج الدلالي عندما يحتوي كلا المصدرين على نية هندسية صالحة.',
    ],
    keywords: ['conflicts', 'clash', 'resolve', 'merge', 'source', 'version', 'تعارضات', 'حل', 'دمج', 'مصدر'],
    relatedTopics: related.conflicts,
    navigateTo: '/conflicts',
  },
  'settings.backend': {
    id: 'settings.backend',
    category: 'settings',
    titleEn: 'Backend settings',
    titleAr: 'إعدادات الخادم الخلفي',
    descriptionEn: 'Configure API timeout, retry behavior, and backend connectivity expectations.',
    descriptionAr: 'اضبط مهلة API وسلوك إعادة المحاولة وتوقعات الاتصال بالخادم الخلفي.',
    stepsEn: [
      'Open Settings and select the API tab.',
      'Set an API timeout that matches your network latency.',
      'Set retry attempts for transient network failures.',
      'Save settings and use Refresh Health to verify connectivity.',
    ],
    stepsAr: [
      'افتح الإعدادات واختر تبويب API.',
      'اضبط مهلة API بما يتناسب مع زمن انتقال الشبكة.',
      'اضبط محاولات إعادة المحاولة للأعطال الشبكية المؤقتة.',
      'احفظ الإعدادات واستخدم تحديث الحالة للتحقق من الاتصال.',
    ],
    warningsEn: [
      'Very short timeouts can cause false backend failures.',
      'High retry counts may increase load during outages.',
    ],
    warningsAr: [
      'قد تؤدي المهلات القصيرة جدًا إلى إخفاقات خلفية زائفة.',
      'قد تزيد أعداد إعادة المحاولة العالية من الحمل أثناء الأعطال.',
    ],
    keywords: ['settings', 'backend', 'API', 'timeout', 'retry', 'health', 'إعدادات', 'خادم', 'مهلة', 'إعادة المحاولة'],
    relatedTopics: related.settings,
    navigateTo: '/settings',
  },
  'troubleshooting.backend': {
    id: 'troubleshooting.backend',
    category: 'troubleshooting',
    titleEn: 'Backend troubleshooting',
    titleAr: 'استكشاف أخطاء الخادم الخلفي',
    descriptionEn: 'Diagnose backend startup, port, and health-check issues.',
    descriptionAr: 'شخّص مشكلات بدء الخادم الخلفي والمنفذ وفحص الحالة.',
    stepsEn: [
      'Check the backend status badge in the top bar.',
      'Verify the API base URL in environment settings.',
      'Confirm the backend process is listening on the expected port.',
      'Review backend logs for startup errors or database connection failures.',
    ],
    stepsAr: [
      'تحقق من شارة حالة الخادم الخلفي في الشريط العلوي.',
      'تأكد من صحة عنوان API الأساسي في إعدادات البيئة.',
      'أكد أن عملية الخادم الخلفي تستمع على المنفذ المتوقع.',
      'راجع سجلات الخادم الخلفي بحثًا عن أخطاء بدء التشغيل أو فشل قاعدة البيانات.',
    ],
    warningsEn: [
      'Do not change production backend URLs without confirming the target environment.',
      'If an API key is required, ensure it is available to the running process.',
    ],
    warningsAr: [
      'لا تغير عناوين الخادم الخلفي للإنتاج دون تأكيد بيئة الهدف.',
      'إذا كانت هناك حاجة إلى مفتاح API فتأكد من توفره للعملية الجارية.',
    ],
    keywords: ['backend', 'server', 'health', 'port', 'startup', 'database', 'API key', 'خادم', 'منفذ', 'قاعدة بيانات'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.api': {
    id: 'troubleshooting.api',
    category: 'troubleshooting',
    titleEn: 'API troubleshooting',
    titleAr: 'استكشاف أخطاء API',
    descriptionEn: 'Resolve failed API requests, timeouts, authentication errors, and stale data.',
    descriptionAr: 'حل أعطال طلبات API والمهلات وأخطاء المصادقة والبيانات القديمة.',
    stepsEn: [
      'Open Smart Help and search for API, timeout, or the failing page name.',
      'Refresh the page that failed and retry once.',
      'Check the backend status badge and network connectivity.',
      'If the error persists, capture the route, timestamp, and error message for support.',
    ],
    stepsAr: [
      'افتح المساعدة الذكية وابحث عن API أو مهلة أو اسم الصفحة التي فشلت.',
      'حدّث الصفحة التي فشلت وحاول مرة أخرى.',
      'تحقق من شارة حالة الخادم الخلفي واتصال الشبكة.',
      'إذا استمر الخطأ فالتقط المسار والطابع الزمني ورسالة الخطأ للدعم.',
    ],
    warningsEn: [
      'Repeated retries can duplicate write operations.',
      'Do not paste secrets or API keys into support notes.',
    ],
    warningsAr: [
      'قد تؤدي إعادة المحاولة المتكررة إلى تكرار عمليات الكتابة.',
      'لا تلصق الأسرار أو مفاتيح API في ملاحظات الدعم.',
    ],
    keywords: ['api', 'request', 'timeout', 'network', 'error', 'retry', 'authentication', 'API', 'طلب', 'مهلة', 'شبكة'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.auth': {
    id: 'troubleshooting.auth',
    category: 'troubleshooting',
    titleEn: 'Authentication troubleshooting',
    titleAr: 'استكشاف أخطاء المصادقة',
    descriptionEn: 'Resolve login, token, API key, and permission issues.',
    descriptionAr: 'حل مشكلات تسجيل الدخول والرموز ومفاتيح API والأذونات.',
    stepsEn: [
      'Confirm you are signed in to the expected FireAI environment.',
      'Check whether the API key is configured in the active environment.',
      'Refresh the session if tokens may have expired.',
      'Contact an administrator if the account lacks the required project permissions.',
    ],
    stepsAr: [
      'تأكد من تسجيل الدخول إلى بيئة FireAI الصحيحة.',
      'تحقق مما إذا كان مفتاح API مُعدًا في البيئة النشطة.',
      'حدّث الجلسة إذا كانت الرموز قد تكون منتهية الصلاحية.',
      'تواصل مع المسؤول إذا كان الحساب لا يملك أذونات المشروع المطلوبة.',
    ],
    warningsEn: [
      'Never share API keys in chat, screenshots, or logs.',
      'Production access should use least-privilege credentials.',
    ],
    warningsAr: [
      'لا تشارك مفاتيح API في المحادثات أو لقطات الشاشة أو السجلات.',
      'ينبغي أن تستخدم صلاحيات الإنتاج مبدأ أقل امتياز.',
    ],
    keywords: ['auth', 'login', 'token', 'API key', 'permission', 'access', 'مصادقة', 'دخول', 'رمز', 'صلاحية'],
    relatedTopics: related.troubleshooting,
  },
  'troubleshooting.app-crash': {
    id: 'troubleshooting.app-crash',
    category: 'troubleshooting',
    titleEn: 'Application crash recovery',
    titleAr: 'استعادة التطبيق بعد تعطل',
    descriptionEn: 'Recover from an unexpected application crash while preserving project data where possible.',
    descriptionAr: 'استعد بعد تعطل غير متوقع في التطبيق مع الحفاظ على بيانات المشروع قدر الإمكان.',
    stepsEn: [
      'Use Reload Application to remount the React shell.',
      'If the crash repeats on the same page, open the previous page from the sidebar.',
      'Check backend health before retrying data-heavy actions.',
      'Report the route, recent action, and error details to support.',
    ],
    stepsAr: [
      'استخدم إعادة تحميل التطبيق لإعادة تركيب واجهة React.',
      'إذا تكرر التعطل في الصفحة نفسها فافتح الصفحة السابقة من الشريط الجانبي.',
      'تحقق من صحة الخادم الخلفي قبل إعادة إجراءات البيانات الكثيفة.',
      'أبلغ الدعم بالمسار والإجراء الأخير وتفاصيل الخطأ.',
    ],
    warningsEn: [
      'Reloading may discard unsaved draft changes.',
      'If the error boundary shows sensitive data, avoid sharing screenshots publicly.',
    ],
    warningsAr: [
      'قد يؤدي إعادة التحميل إلى فقدان تغييرات المسودة غير المحفوظة.',
      'إذا أظهر حد الخطأ بيانات حساسة فتجنب مشاركة لقطات الشاشة علنًا.',
    ],
    keywords: ['crash', 'reload', 'error boundary', 'fatal', 'application', 'تعطل', 'إعادة تحميل', 'خطأ'],
    relatedTopics: related.troubleshooting,
  },
};

export const HELP_TOPIC_ORDER: HelpTopicId[] = Object.values(HELP_TOPICS)
  .sort((a, b) => a.category.localeCompare(b.category) || a.id.localeCompare(b.id))
  .map((topic) => topic.id);

export const HELP_CATEGORY_LABELS: Record<HelpCategory, { en: string; ar: string }> = {
  dashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  projects: { en: 'Projects', ar: 'المشاريع' },
  engineering: { en: 'Engineering', ar: 'الهندسة' },
  'fire-alarm': { en: 'Fire Alarm', ar: 'الإنذار' },
  reports: { en: 'Reports', ar: 'التقارير' },
  'digital-twin': { en: 'Digital Twin', ar: 'التوأم الرقمي' },
  elements: { en: 'Elements', ar: 'العناصر' },
  connections: { en: 'Connections', ar: 'الاتصالات' },
  conflicts: { en: 'Conflicts', ar: 'التعارضات' },
  settings: { en: 'Settings', ar: 'الإعدادات' },
  troubleshooting: { en: 'Troubleshooting', ar: 'استكشاف الأخطاء' },
  general: { en: 'General', ar: 'عام' },
};
