"""marine/core — Domain types, constants, and errors."""
from marine.core.types import (
    AlarmLevel,
    AlarmLogicNode,
    ComplianceResult,
    DetectorPlacement,
    DetectorType,
    ExtinguishingDesign,
    ExtinguishingSystem,
    FireClass,
    FireHazardClass,
    FireResistanceSpec,
    MarineZone,
    ShipElectricalSpec,
    ShipProject,
    ShipService,
    ShipType,
    SpaceCategory,
    ThermalAlarmClass,
)

__all__ = [
    "AlarmLevel",
    "AlarmLogicNode",
    "ComplianceResult",
    "DetectorPlacement",
    "DetectorType",
    "ExtinguishingDesign",
    "ExtinguishingSystem",
    "FireClass",
    "FireHazardClass",
    "FireResistanceSpec",
    "MarineZone",
    "ShipElectricalSpec",
    "ShipProject",
    "ShipService",
    "ShipType",
    "SpaceCategory",
    "ThermalAlarmClass",
]
