/**
 * deviceLibrary.ts - Comprehensive Light Current Device Library
 * 38 devices across 6 categories with AutoCAD/Revit/IFC mappings
 */

export type DeviceCategory =
	| "FIRE_ALARM"
	| "SECURITY"
	| "CCTV"
	| "DATA_NETWORK"
	| "PA_SYSTEM"
	| "TELEPHONE";

export interface DeviceSpec {
	id: string;
	name: string;
	category: DeviceCategory;
	description: string;
	symbol: string;
	defaultVoltage: number;
	defaultCurrent: number;
	defaultLoad: number;
	width: number;
	height: number;
	autocadBlock: string;
	revitFamily: string;
	revitType: string;
	ifcClass: string;
	ifcType: string;
	tags: string[];
}

export const DEVICE_LIBRARY: DeviceSpec[] = [
	// FIRE ALARM (8 devices)
	{
		id: "FA_SMOKE_DET",
		name: "Smoke Detector",
		category: "FIRE_ALARM",
		description: "Photoelectric smoke detector, ceiling mounted",
		symbol: "SD",
		defaultVoltage: 24,
		defaultCurrent: 0.05,
		defaultLoad: 1.2,
		width: 40,
		height: 40,
		autocadBlock: "FIRE_SMOKE_DET_CEIL",
		revitFamily: "Fire Alarm Devices",
		revitType: "Smoke Detector",
		ifcClass: "IfcFireSuppressionTerminal",
		ifcType: "SMOKEDETECTOR",
		tags: ["fire", "smoke", "detection", "ceiling"],
	},
	{
		id: "FA_HEAT_DET",
		name: "Heat Detector",
		category: "FIRE_ALARM",
		description: "Fixed temperature heat detector",
		symbol: "HD",
		defaultVoltage: 24,
		defaultCurrent: 0.04,
		defaultLoad: 0.96,
		width: 40,
		height: 40,
		autocadBlock: "FIRE_HEAT_DET_CEIL",
		revitFamily: "Fire Alarm Devices",
		revitType: "Heat Detector",
		ifcClass: "IfcFireSuppressionTerminal",
		ifcType: "HEATDETECTOR",
		tags: ["fire", "heat", "detection", "ceiling"],
	},
	{
		id: "FA_MANUAL_CALL",
		name: "Manual Call Point",
		category: "FIRE_ALARM",
		description: "Break glass manual fire alarm call point",
		symbol: "MCP",
		defaultVoltage: 24,
		defaultCurrent: 0.02,
		defaultLoad: 0.48,
		width: 30,
		height: 50,
		autocadBlock: "FIRE_MANUAL_CALL",
		revitFamily: "Fire Alarm Devices",
		revitType: "Manual Call Point",
		ifcClass: "IfcFireSuppressionTerminal",
		ifcType: "MANUALCALLPOINT",
		tags: ["fire", "manual", "alarm", "wall"],
	},
	{
		id: "FA_SOUND_STROBE",
		name: "Sounder Strobe",
		category: "FIRE_ALARM",
		description: "Combined audible sounder and visual strobe",
		symbol: "SS",
		defaultVoltage: 24,
		defaultCurrent: 0.15,
		defaultLoad: 3.6,
		width: 50,
		height: 50,
		autocadBlock: "FIRE_SOUNDER_STROBE",
		revitFamily: "Fire Alarm Devices",
		revitType: "Sounder Strobe",
		ifcClass: "IfcAlarmDevice",
		ifcType: "SOUNDERSTROBE",
		tags: ["fire", "sounder", "strobe", "alarm"],
	},
	{
		id: "FA_CONTROL_PANEL",
		name: "Fire Alarm Control Panel",
		category: "FIRE_ALARM",
		description: "Addressable fire alarm control panel (FACP)",
		symbol: "FACP",
		defaultVoltage: 230,
		defaultCurrent: 2.0,
		defaultLoad: 460,
		width: 120,
		height: 160,
		autocadBlock: "FIRE_CONTROL_PANEL",
		revitFamily: "Fire Alarm Devices",
		revitType: "Control Panel",
		ifcClass: "IfcController",
		ifcType: "FIREALARMCONTROL",
		tags: ["fire", "control", "panel", "facp"],
	},
	{
		id: "FA_INPUT_MODULE",
		name: "Monitor Module",
		category: "FIRE_ALARM",
		description: "Addressable input/monitor module",
		symbol: "MM",
		defaultVoltage: 24,
		defaultCurrent: 0.01,
		defaultLoad: 0.24,
		width: 30,
		height: 30,
		autocadBlock: "FIRE_MONITOR_MODULE",
		revitFamily: "Fire Alarm Devices",
		revitType: "Monitor Module",
		ifcClass: "IfcController",
		ifcType: "MONITORMODULE",
		tags: ["fire", "monitor", "module", "input"],
	},
	{
		id: "FA_OUTPUT_MODULE",
		name: "Control Module",
		category: "FIRE_ALARM",
		description: "Addressable output/control module",
		symbol: "CM",
		defaultVoltage: 24,
		defaultCurrent: 0.08,
		defaultLoad: 1.92,
		width: 30,
		height: 30,
		autocadBlock: "FIRE_CONTROL_MODULE",
		revitFamily: "Fire Alarm Devices",
		revitType: "Control Module",
		ifcClass: "IfcController",
		ifcType: "CONTROLMODULE",
		tags: ["fire", "control", "module", "output"],
	},
	{
		id: "FA_ISOLATOR",
		name: "Short Circuit Isolator",
		category: "FIRE_ALARM",
		description: "Loop isolator for short circuit protection",
		symbol: "SCI",
		defaultVoltage: 24,
		defaultCurrent: 0.01,
		defaultLoad: 0.24,
		width: 25,
		height: 25,
		autocadBlock: "FIRE_ISOLATOR",
		revitFamily: "Fire Alarm Devices",
		revitType: "Short Circuit Isolator",
		ifcClass: "IfcProtectiveDevice",
		ifcType: "SHORTCIRCUITISOLATOR",
		tags: ["fire", "isolator", "protection", "loop"],
	},

	// SECURITY (6 devices)
	{
		id: "SEC_ACCESS_CTRL",
		name: "Access Control Panel",
		category: "SECURITY",
		description: "Door access controller with RFID support",
		symbol: "ACP",
		defaultVoltage: 12,
		defaultCurrent: 0.5,
		defaultLoad: 6,
		width: 80,
		height: 100,
		autocadBlock: "SEC_ACCESS_CTRL",
		revitFamily: "Security Devices",
		revitType: "Access Control Panel",
		ifcClass: "IfcController",
		ifcType: "ACCESSCONTROL",
		tags: ["security", "access", "control", "rfid"],
	},
	{
		id: "SEC_CARD_READER",
		name: "Card Reader",
		category: "SECURITY",
		description: "Proximity card reader for access control",
		symbol: "CR",
		defaultVoltage: 12,
		defaultCurrent: 0.1,
		defaultLoad: 1.2,
		width: 25,
		height: 40,
		autocadBlock: "SEC_CARD_READER",
		revitFamily: "Security Devices",
		revitType: "Card Reader",
		ifcClass: "IfcSensor",
		ifcType: "CARDREADER",
		tags: ["security", "card", "reader", "access"],
	},
	{
		id: "SEC_MAGNETIC_LOCK",
		name: "Magnetic Lock",
		category: "SECURITY",
		description: "Electromagnetic door lock, 600lb holding force",
		symbol: "ML",
		defaultVoltage: 12,
		defaultCurrent: 0.5,
		defaultLoad: 6,
		width: 60,
		height: 20,
		autocadBlock: "SEC_MAGNETIC_LOCK",
		revitFamily: "Security Devices",
		revitType: "Magnetic Lock",
		ifcClass: "IfcActuator",
		ifcType: "MAGNETICLOCK",
		tags: ["security", "lock", "magnetic", "door"],
	},
	{
		id: "SEC_REX_SENSOR",
		name: "Request to Exit Sensor",
		category: "SECURITY",
		description: "Motion sensor for door exit request",
		symbol: "REX",
		defaultVoltage: 12,
		defaultCurrent: 0.05,
		defaultLoad: 0.6,
		width: 30,
		height: 30,
		autocadBlock: "SEC_REX_SENSOR",
		revitFamily: "Security Devices",
		revitType: "REX Sensor",
		ifcClass: "IfcSensor",
		ifcType: "REQUESTTOEXIT",
		tags: ["security", "rex", "exit", "sensor"],
	},
	{
		id: "SEC_IR_SENSOR",
		name: "Intrusion Detector (PIR)",
		category: "SECURITY",
		description: "Passive infrared motion detector",
		symbol: "PIR",
		defaultVoltage: 12,
		defaultCurrent: 0.03,
		defaultLoad: 0.36,
		width: 35,
		height: 35,
		autocadBlock: "SEC_IR_SENSOR",
		revitFamily: "Security Devices",
		revitType: "PIR Sensor",
		ifcClass: "IfcSensor",
		ifcType: "MOTIONDETECTOR",
		tags: ["security", "pir", "motion", "intrusion"],
	},
	{
		id: "SEC_DOOR_CONTACT",
		name: "Door Contact Sensor",
		category: "SECURITY",
		description: "Magnetic door contact for status monitoring",
		symbol: "DCS",
		defaultVoltage: 12,
		defaultCurrent: 0.01,
		defaultLoad: 0.12,
		width: 20,
		height: 15,
		autocadBlock: "SEC_DOOR_CONTACT",
		revitFamily: "Security Devices",
		revitType: "Door Contact",
		ifcClass: "IfcSensor",
		ifcType: "DOORCONTACT",
		tags: ["security", "door", "contact", "sensor"],
	},

	// CCTV (8 devices)
	{
		id: "CCTV_DOME",
		name: "Dome Camera",
		category: "CCTV",
		description: "Indoor dome IP camera, 4MP, IR",
		symbol: "DOME",
		defaultVoltage: 12,
		defaultCurrent: 0.5,
		defaultLoad: 6,
		width: 45,
		height: 45,
		autocadBlock: "CCTV_DOME",
		revitFamily: "Security Devices",
		revitType: "Dome Camera",
		ifcClass: "IfcSensor",
		ifcType: "DOMECAMERA",
		tags: ["cctv", "camera", "dome", "indoor"],
	},
	{
		id: "CCTV_BULLET",
		name: "Bullet Camera",
		category: "CCTV",
		description: "Outdoor bullet IP camera, 8MP, IR, IP67",
		symbol: "BULLET",
		defaultVoltage: 12,
		defaultCurrent: 0.7,
		defaultLoad: 8.4,
		width: 50,
		height: 30,
		autocadBlock: "CCTV_BULLET",
		revitFamily: "Security Devices",
		revitType: "Bullet Camera",
		ifcClass: "IfcSensor",
		ifcType: "BULLETCAMERA",
		tags: ["cctv", "camera", "bullet", "outdoor"],
	},
	{
		id: "CCTV_PTZ",
		name: "PTZ Camera",
		category: "CCTV",
		description: "Pan-tilt-zoom IP camera, 20x optical zoom",
		symbol: "PTZ",
		defaultVoltage: 24,
		defaultCurrent: 1.0,
		defaultLoad: 24,
		width: 60,
		height: 60,
		autocadBlock: "CCTV_PTZ",
		revitFamily: "Security Devices",
		revitType: "PTZ Camera",
		ifcClass: "IfcSensor",
		ifcType: "PTZCAMERA",
		tags: ["cctv", "camera", "ptz", "zoom"],
	},
	{
		id: "CCTV_NVR",
		name: "Network Video Recorder",
		category: "CCTV",
		description: "32-channel NVR with 8TB storage",
		symbol: "NVR",
		defaultVoltage: 230,
		defaultCurrent: 1.5,
		defaultLoad: 345,
		width: 120,
		height: 60,
		autocadBlock: "CCTV_NVR",
		revitFamily: "Security Devices",
		revitType: "NVR",
		ifcClass: "IfcController",
		ifcType: "NETWORKVIDEORECORDER",
		tags: ["cctv", "nvr", "recorder", "storage"],
	},
	{
		id: "CCTV_MONITOR",
		name: "CCTV Monitor",
		category: "CCTV",
		description: '55" 4K security monitor',
		symbol: "MON",
		defaultVoltage: 230,
		defaultCurrent: 0.8,
		defaultLoad: 184,
		width: 140,
		height: 80,
		autocadBlock: "CCTV_MONITOR",
		revitFamily: "Security Devices",
		revitType: "Monitor",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "MONITOR",
		tags: ["cctv", "monitor", "display", "4k"],
	},
	{
		id: "CCTV_POE_SWITCH",
		name: "PoE Switch (CCTV)",
		category: "CCTV",
		description: "16-port PoE+ switch for cameras",
		symbol: "POE",
		defaultVoltage: 230,
		defaultCurrent: 2.0,
		defaultLoad: 460,
		width: 100,
		height: 40,
		autocadBlock: "CCTV_POE_SWITCH",
		revitFamily: "Communication Devices",
		revitType: "PoE Switch",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "POESWITCH",
		tags: ["cctv", "poe", "switch", "network"],
	},
	{
		id: "CCTV_JUNCTION",
		name: "Camera Junction Box",
		category: "CCTV",
		description: "Weatherproof junction box for camera connections",
		symbol: "JB",
		defaultVoltage: 0,
		defaultCurrent: 0,
		defaultLoad: 0,
		width: 30,
		height: 30,
		autocadBlock: "CCTV_JUNCTION",
		revitFamily: "Communication Devices",
		revitType: "Junction Box",
		ifcClass: "IfcJunctionBox",
		ifcType: "CAMERAJUNCTION",
		tags: ["cctv", "junction", "box", "weatherproof"],
	},
	{
		id: "CCTV_IR_ILLUMINATOR",
		name: "IR Illuminator",
		category: "CCTV",
		description: "External IR illuminator, 50m range",
		symbol: "IR",
		defaultVoltage: 12,
		defaultCurrent: 1.0,
		defaultLoad: 12,
		width: 40,
		height: 40,
		autocadBlock: "CCTV_IR_ILLUMINATOR",
		revitFamily: "Security Devices",
		revitType: "IR Illuminator",
		ifcClass: "IfcLightFixture",
		ifcType: "IRILLUMINATOR",
		tags: ["cctv", "ir", "illuminator", "night"],
	},

	// DATA NETWORK (6 devices)
	{
		id: "DATA_AP",
		name: "Wireless Access Point",
		category: "DATA_NETWORK",
		description: "Ceiling mount Wi-Fi 6 access point",
		symbol: "AP",
		defaultVoltage: 48,
		defaultCurrent: 0.3,
		defaultLoad: 14.4,
		width: 50,
		height: 50,
		autocadBlock: "DATA_ACCESS_POINT",
		revitFamily: "Communication Devices",
		revitType: "Access Point",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "ACCESSPOINT",
		tags: ["data", "wifi", "access point", "wireless"],
	},
	{
		id: "DATA_SWITCH",
		name: "Network Switch",
		category: "DATA_NETWORK",
		description: "48-port managed L3 switch",
		symbol: "SW",
		defaultVoltage: 230,
		defaultCurrent: 1.2,
		defaultLoad: 276,
		width: 100,
		height: 40,
		autocadBlock: "DATA_SWITCH",
		revitFamily: "Communication Devices",
		revitType: "Network Switch",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "NETWORKSWITCH",
		tags: ["data", "switch", "network", "managed"],
	},
	{
		id: "DATA_ROUTER",
		name: "Core Router",
		category: "DATA_NETWORK",
		description: "Enterprise core router",
		symbol: "RTR",
		defaultVoltage: 230,
		defaultCurrent: 2.0,
		defaultLoad: 460,
		width: 100,
		height: 50,
		autocadBlock: "DATA_ROUTER",
		revitFamily: "Communication Devices",
		revitType: "Router",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "ROUTER",
		tags: ["data", "router", "core", "enterprise"],
	},
	{
		id: "DATA_PATCH_PANEL",
		name: "Patch Panel",
		category: "DATA_NETWORK",
		description: "24-port Cat6A patch panel",
		symbol: "PP",
		defaultVoltage: 0,
		defaultCurrent: 0,
		defaultLoad: 0,
		width: 80,
		height: 30,
		autocadBlock: "DATA_PATCH_PANEL",
		revitFamily: "Communication Devices",
		revitType: "Patch Panel",
		ifcClass: "IfcCableCarrierFitting",
		ifcType: "PATCHPANEL",
		tags: ["data", "patch", "panel", "cat6a"],
	},
	{
		id: "DATA_SERVER_RACK",
		name: "Server Rack",
		category: "DATA_NETWORK",
		description: "42U server rack enclosure",
		symbol: "SR",
		defaultVoltage: 230,
		defaultCurrent: 10.0,
		defaultLoad: 2300,
		width: 120,
		height: 200,
		autocadBlock: "DATA_SERVER_RACK",
		revitFamily: "Communication Devices",
		revitType: "Server Rack",
		ifcClass: "IfcFurniture",
		ifcType: "SERVERRACK",
		tags: ["data", "server", "rack", "42u"],
	},
	{
		id: "DATA_FIBER_ENCLOSURE",
		name: "Fiber Optic Enclosure",
		category: "DATA_NETWORK",
		description: "Fiber optic termination enclosure, 24 cores",
		symbol: "FOE",
		defaultVoltage: 0,
		defaultCurrent: 0,
		defaultLoad: 0,
		width: 60,
		height: 40,
		autocadBlock: "DATA_FIBER_ENCLOSURE",
		revitFamily: "Communication Devices",
		revitType: "Fiber Enclosure",
		ifcClass: "IfcCableCarrierFitting",
		ifcType: "FIBEROPTICENCLOSURE",
		tags: ["data", "fiber", "optic", "enclosure"],
	},

	// PA SYSTEM (5 devices)
	{
		id: "PA_CEILING_SPEAKER",
		name: "Ceiling Speaker",
		category: "PA_SYSTEM",
		description: "6W ceiling mounted speaker, 100V line",
		symbol: "CS",
		defaultVoltage: 100,
		defaultCurrent: 0.06,
		defaultLoad: 6,
		width: 40,
		height: 40,
		autocadBlock: "PA_CEILING_SPEAKER",
		revitFamily: "Fire Alarm Devices",
		revitType: "Ceiling Speaker",
		ifcClass: "IfcAudioVisualAppliance",
		ifcType: "CEILINGSPEAKER",
		tags: ["pa", "speaker", "ceiling", "100v"],
	},
	{
		id: "PA_WALL_SPEAKER",
		name: "Wall Speaker",
		category: "PA_SYSTEM",
		description: "10W wall mounted horn speaker",
		symbol: "WS",
		defaultVoltage: 100,
		defaultCurrent: 0.1,
		defaultLoad: 10,
		width: 40,
		height: 50,
		autocadBlock: "PA_WALL_SPEAKER",
		revitFamily: "Fire Alarm Devices",
		revitType: "Wall Speaker",
		ifcClass: "IfcAudioVisualAppliance",
		ifcType: "WALLSPEAKER",
		tags: ["pa", "speaker", "wall", "horn"],
	},
	{
		id: "PA_HORN",
		name: "Weatherproof Horn",
		category: "PA_SYSTEM",
		description: "Outdoor weatherproof horn, 15W",
		symbol: "HORN",
		defaultVoltage: 100,
		defaultCurrent: 0.15,
		defaultLoad: 15,
		width: 50,
		height: 60,
		autocadBlock: "PA_HORN",
		revitFamily: "Fire Alarm Devices",
		revitType: "Horn Speaker",
		ifcClass: "IfcAudioVisualAppliance",
		ifcType: "HORNSPEAKER",
		tags: ["pa", "horn", "outdoor", "weatherproof"],
	},
	{
		id: "PA_AMPLIFIER",
		name: "PA Amplifier",
		category: "PA_SYSTEM",
		description: "240W public address amplifier",
		symbol: "AMP",
		defaultVoltage: 230,
		defaultCurrent: 2.0,
		defaultLoad: 460,
		width: 100,
		height: 60,
		autocadBlock: "PA_AMPLIFIER",
		revitFamily: "Fire Alarm Devices",
		revitType: "Amplifier",
		ifcClass: "IfcAudioVisualAppliance",
		ifcType: "AMPLIFIER",
		tags: ["pa", "amplifier", "240w", "rack"],
	},
	{
		id: "PA_MICROPHONE",
		name: "Zone Microphone",
		category: "PA_SYSTEM",
		description: "Zone selection paging microphone",
		symbol: "MIC",
		defaultVoltage: 24,
		defaultCurrent: 0.05,
		defaultLoad: 1.2,
		width: 30,
		height: 40,
		autocadBlock: "PA_MICROPHONE",
		revitFamily: "Fire Alarm Devices",
		revitType: "Microphone",
		ifcClass: "IfcAudioVisualAppliance",
		ifcType: "MICROPHONE",
		tags: ["pa", "microphone", "paging", "zone"],
	},

	// TELEPHONE (5 devices)
	{
		id: "TEL_OUTLET",
		name: "Telephone Outlet",
		category: "TELEPHONE",
		description: "RJ11 telephone wall outlet",
		symbol: "TO",
		defaultVoltage: 48,
		defaultCurrent: 0.02,
		defaultLoad: 0.96,
		width: 25,
		height: 25,
		autocadBlock: "TEL_OUTLET",
		revitFamily: "Communication Devices",
		revitType: "Telephone Outlet",
		ifcClass: "IfcOutlet",
		ifcType: "TELEPHONEOUTLET",
		tags: ["telephone", "outlet", "rj11", "wall"],
	},
	{
		id: "TEL_PBX",
		name: "PBX System",
		category: "TELEPHONE",
		description: "IP-PBX telephone exchange system",
		symbol: "PBX",
		defaultVoltage: 230,
		defaultCurrent: 3.0,
		defaultLoad: 690,
		width: 120,
		height: 160,
		autocadBlock: "TEL_PBX",
		revitFamily: "Communication Devices",
		revitType: "PBX System",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "PBXSYSTEM",
		tags: ["telephone", "pbx", "exchange", "ip"],
	},
	{
		id: "TEL_MDF",
		name: "Main Distribution Frame",
		category: "TELEPHONE",
		description: "Main distribution frame for telephone cabling",
		symbol: "MDF",
		defaultVoltage: 0,
		defaultCurrent: 0,
		defaultLoad: 0,
		width: 100,
		height: 180,
		autocadBlock: "TEL_MDF",
		revitFamily: "Communication Devices",
		revitType: "MDF",
		ifcClass: "IfcCableCarrierFitting",
		ifcType: "MAINDISTRIBUTIONFRAME",
		tags: ["telephone", "mdf", "distribution", "frame"],
	},
	{
		id: "TEL_IDF",
		name: "Intermediate Distribution Frame",
		category: "TELEPHONE",
		description: "Intermediate distribution frame",
		symbol: "IDF",
		defaultVoltage: 0,
		defaultCurrent: 0,
		defaultLoad: 0,
		width: 80,
		height: 120,
		autocadBlock: "TEL_IDF",
		revitFamily: "Communication Devices",
		revitType: "IDF",
		ifcClass: "IfcCableCarrierFitting",
		ifcType: "INTERMEDIATEDISTRIBUTIONFRAME",
		tags: ["telephone", "idf", "distribution", "frame"],
	},
	{
		id: "TEL_VOICEMAIL",
		name: "Voicemail Server",
		category: "TELEPHONE",
		description: "Voicemail and auto-attendant server",
		symbol: "VMS",
		defaultVoltage: 230,
		defaultCurrent: 1.0,
		defaultLoad: 230,
		width: 80,
		height: 100,
		autocadBlock: "TEL_VOICEMAIL",
		revitFamily: "Communication Devices",
		revitType: "Voicemail Server",
		ifcClass: "IfcCommunicationsAppliance",
		ifcType: "VOICEMAILSERVER",
		tags: ["telephone", "voicemail", "server", "auto-attendant"],
	},
];

export const DEVICE_CATEGORIES: {
	id: DeviceCategory;
	label: string;
	count: number;
}[] = [
	{ id: "FIRE_ALARM", label: "Fire Alarm", count: 8 },
	{ id: "SECURITY", label: "Security & Access", count: 6 },
	{ id: "CCTV", label: "CCTV & Surveillance", count: 8 },
	{ id: "DATA_NETWORK", label: "Data Network", count: 6 },
	{ id: "PA_SYSTEM", label: "PA & Voice Alarm", count: 5 },
	{ id: "TELEPHONE", label: "Telephone", count: 5 },
];

export function getDevicesByCategory(category: DeviceCategory): DeviceSpec[] {
	return DEVICE_LIBRARY.filter((d) => d.category === category);
}

export function getDeviceById(id: string): DeviceSpec | undefined {
	return DEVICE_LIBRARY.find((d) => d.id === id);
}

export function searchDevices(query: string): DeviceSpec[] {
	const q = query.toLowerCase();
	return DEVICE_LIBRARY.filter(
		(d) =>
			d.name.toLowerCase().includes(q) ||
			d.id.toLowerCase().includes(q) ||
			d.description.toLowerCase().includes(q) ||
			d.tags.some((t) => t.toLowerCase().includes(q)),
	);
}
