"""
BETA ONLY Watermark - Safety Marking
===============================

Adds BETA ONLY watermark to output reports.
This is a critical safety feature to prevent misuse.
"""

import os
from datetime import datetime


BETA_WATERMARK = """
╔══════════════════════════════════════════════════════════════════════════╗
║  ⚠️  BETA SOFTWARE — NOT FOR PRODUCTION USE                    ║
║                                                                  ║
║  This output was generated by BETA software that has NOT been   ║
║  reviewed by a licensed Fire Protection Engineer (FPE).          ║
║                                                                  ║
║  ALL RESULTS REQUIRE FPE REVIEW BEFORE USE              ║
║                                                                  ║
║  Using this output for final design WITHOUT FPE review      ║
║  may result in:                                          ║
║  → System non-compliance with NFPA 72                      ║
║  → Legal liability                                     ║
║  → Injury or death                                      ║
╚══════════════════════════════════════════════════════════════════════════╝
"""


def add_watermark_to_text(text: str) -> str:
    """Add BETA watermark to text output."""
    header = BETA_WATERMARK
    separator = "=" * 60 + "\n"
    
    return f"{header}\n{separator}{text}"


def add_watermark_to_csv(csv_path: str) -> str:
    """Add BETA watermark as CSV header comment."""
    if not os.path.exists(csv_path):
        return csv_path
    
    # Read existing CSV
    with open(csv_path, 'r') as f:
        content = f.read()
    
    # Add watermark as comment at top
    watermark_lines = [
        "# " + "=" * 58,
        "# ⚠️  BETA SOFTWARE — NOT FOR PRODUCTION USE",
        "# This output requires FPE review before use.",
        "# " + "=" * 58,
        "",
    ]
    
    # Prepend to content
    new_content = "\n".join(watermark_lines) + "\n" + content
    
    # Write back
    with open(csv_path, 'w') as f:
        f.write(new_content)
    
    return csv_path


def add_watermark_to_dict(data: dict) -> dict:
    """Add BETA warning to output data."""
    return {
        **data,
        '_beta_warning': True,
        '_generated_at': datetime.utcnow().isoformat() + 'Z',
        '_fpe_review_required': True,
    }


if __name__ == "__main__":
    print(add_watermark_to_text("Sample analysis output"))