"""ugld_acoustics.py — Ultrasonic Gas Leak Detection (UGLD) Acoustic Physics Engine
==================================================================================
V23 — Parallel Acoustic Detection Layer

Solves the fatal Line-of-Sight limitation of optical detectors (OGI/Flame) by
modeling ultrasonic acoustic propagation from pressurized gas leaks. UGLD sensors
detect the ultrasonic noise (25 kHz - 100 kHz) generated by gas escaping an
orifice, which propagates spherically regardless of line-of-sight.

This module implements deterministic, physics-based point-to-point acoustic
propagation. Ray tracing (reflections, diffraction, obstruction shadowing)
is explicitly DEFERRED to a later phase — we lock down the free-field physics
first, as we did with Layer 5 (Flame Detector Ray Trace).

Acoustic Physics Laws (Tier 1 — Deterministic):
  1. Speed of Sound (Temperature Dependent):
       c = 331.3 * sqrt(1 + T/273.15)
     Reference: ISO 9613-1:1993 §5, ANSI S1.26-1995

  2. Spherical Divergence (Inverse Square Law):
       SPL(R) = SPL(R_ref) - 20 * log10(R / R_ref)
     Sound pressure level drops by 6 dB per doubling of distance.
     Reference: ISO 9613-1:1993 §5.2

  3. Atmospheric Attenuation (Frequency Dependent):
       Final_SPL(R) = SPL(R) - (alpha * R)
     Where alpha depends on CENTER FREQUENCY, temperature, and humidity
     per ISO 9613-1:1993 Table 2. High-frequency ultrasonic noise attenuates
     FASTER than low-frequency — this is NOT a flat coefficient.

  4. Signal-to-Noise Ratio (SNR) Trigger:
       Sensor triggers ONLY if Final_SPL >= Background_Noise + 6 dB
       AND Final_SPL >= Sensor Trigger Threshold
     Reference: IEC 61252:1993 (personal sound exposure meters),
                ISA-TR 84.00.07 (augmented safety with acoustic detection)

Architectural Integration:
  - Reads ambient temperature from EnvironmentalContext.ambient_temp_c
    to avoid Dual-Path Inconsistency (the V22 purge taught us that
    duplicate temperature fields create divergent physics paths).
  - Returns structured UGLDTriggerResult (not bool) for audit trail.
  - Uses round(value, 1) for dB — 0.1 dB is below human perception
    threshold and well within engineering precision.

Domain Separation from acoustic_calculator.py:
  acoustic_calculator.py handles NFPA 72 §18.4 audible NOTIFICATION
  (speakers, horns, 500-4000 Hz, dBA weighting).
  This module handles GAS LEAK DETECTION (25,000-100,000 Hz, dB SPL
  unweighted, ultrasonic band). These are completely separate physics
  domains with no overlap.

Standards:
  ISO 9613-1:1993   — Attenuation of sound during propagation outdoors
  ISO 9613-2:1996   — General method of calculation
  IEC 61252:1993    — Personal sound exposure meters
  ISA-TR 84.00.07   — Augmented safety with acoustic gas leak detection
  IEC 60079-29-4    — Gas detectors — performance requirements for
                       open-path (line-of-sight) and point detectors

Usage:
    from fireai.core.ugld_acoustics import (
        UltrasonicSensor, AcousticPropagation, UGLDTriggerResult,
        check_ugld_trigger, atmospheric_attenuation_db_per_m,
    )

    sensor = UltrasonicSensor(
        trigger_threshold_db=74.0,
        background_noise_db=60.0,
    )
    propagation = AcousticPropagation(
        leak_spl_at_1m=100.0,
        distance_meters=15.0,
        center_frequency_hz=40000.0,
        temp_c=40.0,
        relative_humidity_pct=50.0,
    )
    result = check_ugld_trigger(propagation, sensor)
    assert result.triggered
"""

from __future__ import annotations

import math
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field, model_validator

# ===========================================================================
# ISO 9613-1 Atmospheric Attenuation — Frequency-Dependent
# ===========================================================================
# Simplified lookup table for atmospheric attenuation coefficient alpha
# (dB/m) at 20°C, 50% relative humidity for common UGLD center frequencies.
#
# Source: ISO 9613-1:1993 §6, Table 2 (calculated values).
# These values represent PURE atmospheric absorption (molecular relaxation
# of oxygen and nitrogen). They do NOT include geometric spreading.
#
# At ultrasonic frequencies, attenuation increases DRAMATICALLY:
#   25 kHz  ->  ~0.12 dB/m  (long range, lower sensitivity)
#   40 kHz  ->  ~0.50 dB/m  (most common UGLD operating point)
#   55 kHz  ->  ~1.20 dB/m
#   80 kHz  ->  ~3.00 dB/m  (short range only)
#  100 kHz  ->  ~5.50 dB/m  (very short range, high attenuation)
#
# Temperature and humidity corrections are applied via the correction factor
# in atmospheric_attenuation_db_per_m().
_ISO_9613_ALPHA_20C_50RH: dict[float, float] = {
    # center_frequency_hz: alpha_dB_per_m at 20C, 50% RH
    20_000: 0.05,
    25_000: 0.12,
    31_500: 0.25,
    40_000: 0.50,
    50_000: 0.90,
    55_000: 1.20,
    63_000: 1.80,
    80_000: 3.00,
    100_000: 5.50,
}

# Default center frequency for UGLD calculations when not specified.
# 40 kHz is the most common operating frequency for commercial UGLD sensors
# (e.g., General Monitors Gassonic, MSA Senscient).
_DEFAULT_UGLD_FREQUENCY_HZ: float = 40_000.0

# SNR margin required for reliable detection.
# 6 dB = signal must be 4x the noise power (10^(6/10) = 3.98).
# This is a widely accepted minimum for industrial alarm systems.
# Reference: ISA-TR 84.00.07, IEC 61508 SIL determination.
_MIN_SNR_DB: float = 6.0


def atmospheric_attenuation_db_per_m(
    center_frequency_hz: float,
    temp_c: float = 20.0,
    relative_humidity_pct: float = 50.0,
) -> float:
    """Calculate atmospheric attenuation coefficient (dB/m) for ultrasonic frequencies.

    Uses ISO 9613-1:1993 §6 methodology with simplified lookup and correction.
    The base values are computed at 20°C / 50% RH, then temperature and humidity
    corrections are applied.

    At ultrasonic frequencies (25-100 kHz), atmospheric absorption dominates
    over geometric spreading beyond ~10-20m. Using a flat coefficient
    (e.g., 0.5 dB/m) is physically incorrect because:
      - At 25 kHz: actual alpha ≈ 0.12 dB/m (0.5 is 4x too conservative)
      - At 100 kHz: actual alpha ≈ 5.5 dB/m (0.5 is 11x too optimistic)

    The correction for temperature and humidity follows the trend from
    ISO 9613-1:1993 Annex E:
      - Higher temperature → slightly lower alpha (for ultrasonic range)
      - Higher humidity → lower alpha (more molecular relaxation at lower freq)
      - Lower humidity → higher alpha (less absorption by water vapor,
        but more by oxygen relaxation processes at ultrasonic frequencies)

    Args:
        center_frequency_hz: Center frequency of the ultrasonic signal (Hz).
            Typical UGLD: 25,000-100,000 Hz.
        temp_c: Ambient temperature in degrees Celsius.
        relative_humidity_pct: Relative humidity in percent (0-100).

    Returns:
        Atmospheric attenuation coefficient in dB/m. Always positive.

    Reference: ISO 9613-1:1993 §6, Table 2 + Annex E

    """
    # V65 SAFETY: Validate inputs before computation.
    # This is a standalone function (not protected by Pydantic model validation).
    # NaN/Inf inputs produce NaN alpha → NaN SPL → false compliance pass.
    if not math.isfinite(center_frequency_hz) or center_frequency_hz <= 0:
        raise ValueError(
            f"center_frequency_hz must be positive and finite, got {center_frequency_hz}. "
            f"Non-positive or NaN frequency makes atmospheric attenuation undefined."
        )
    if not math.isfinite(temp_c) or temp_c < -40.0 or temp_c > 85.0:
        raise ValueError(
            f"temp_c must be finite and in range [-40, 85]°C, got {temp_c}. "
            f"Outside this range, ISO 9613-1 corrections are unreliable."
        )
    if not math.isfinite(relative_humidity_pct) or relative_humidity_pct < 0.0 or relative_humidity_pct > 100.0:
        raise ValueError(
            f"relative_humidity_pct must be finite and in range [0, 100]%, got {relative_humidity_pct}."
        )

    # Find nearest reference frequency in the lookup table
    ref_freqs = sorted(_ISO_9613_ALPHA_20C_50RH.keys())
    nearest = min(ref_freqs, key=lambda f: abs(f - center_frequency_hz))
    base_alpha = _ISO_9613_ALPHA_20C_50RH[nearest]

    # If the requested frequency is between table entries, interpolate linearly
    if center_frequency_hz != nearest:
        # Find the two bracketing frequencies
        lower = max((f for f in ref_freqs if f <= center_frequency_hz), default=ref_freqs[0])
        upper = min((f for f in ref_freqs if f >= center_frequency_hz), default=ref_freqs[-1])

        if lower != upper:
            alpha_lower = _ISO_9613_ALPHA_20C_50RH[lower]
            alpha_upper = _ISO_9613_ALPHA_20C_50RH[upper]
            # Linear interpolation in log-frequency space
            log_frac = math.log10(center_frequency_hz / lower) / math.log10(upper / lower)
            base_alpha = alpha_lower + log_frac * (alpha_upper - alpha_lower)

    # Temperature correction: at ultrasonic frequencies, higher temperature
    # slightly reduces attenuation. Approximate correction from ISO 9613-1
    # Annex E data: ~-0.3% per degree C above 20°C.
    temp_correction = 1.0 - 0.003 * (temp_c - 20.0)
    temp_correction = max(0.7, min(temp_correction, 1.3))  # Clamp to physical range

    # Humidity correction: at ultrasonic frequencies, moderate humidity (40-60%)
    # produces the minimum attenuation. Very dry (<20%) or very humid (>80%)
    # conditions can increase attenuation. Simplified correction:
    #   - 20-80% RH: minimal correction (0.85-1.1)
    #   - <20%: increased attenuation (up to 1.5x)
    #   - >80%: slightly increased (up to 1.2x)
    if relative_humidity_pct < 20:
        hum_correction = 1.0 + 0.5 * (20.0 - relative_humidity_pct) / 20.0
    elif relative_humidity_pct > 80:
        hum_correction = 1.0 + 0.2 * (relative_humidity_pct - 80.0) / 20.0
    else:
        # 20-80% RH: slight dip around 50% (optimal), peak at edges
        hum_correction = 1.0 - 0.1 * abs(relative_humidity_pct - 50.0) / 30.0
        hum_correction = max(0.85, hum_correction)

    alpha = base_alpha * temp_correction * hum_correction
    return round(alpha, 4)


# ===========================================================================
# Pydantic Models (frozen, strict — project standard)
# ===========================================================================


class UGLDFrequencyBand(str, Enum):
    """Ultrasonic frequency bands for UGLD classification.

    Lower frequencies propagate further but may miss small leaks.
    Higher frequencies detect smaller leaks but have shorter range.
    Reference: IEC 60079-29-4, ISA-TR 84.00.07
    """

    ULTRASOUND_LOW = "ULTRASOUND_LOW"  # 20-35 kHz (long range)
    ULTRASOUND_MID = "ULTRASOUND_MID"  # 35-55 kHz (standard)
    ULTRASOUND_HIGH = "ULTRASOUND_HIGH"  # 55-80 kHz (high sensitivity)
    ULTRASOUND_VHF = "ULTRASOUND_VHF"  # 80-100 kHz (very short range)


class UltrasonicSensor(BaseModel):
    """UGLD sensor specification.

    The trigger_threshold_db is the minimum SPL at the sensor required to
    generate an alarm. The background_noise_db represents the ambient
    ultrasonic noise floor at the installation point — this is NOT a fixed
    property of the sensor but of the installation environment. It should
    come from a site survey or conservative estimate.

    Typical industrial values:
      - Quiet outdoor: 45-55 dB SPL
      - Typical plant: 55-65 dB SPL
      - Noisy compressor area: 65-75 dB SPL
      - Turbine hall: 70-80 dB SPL

    Reference: ISA-TR 84.00.07 §4.3, General Monitors Gassonic Application Guide
    """

    model_config = ConfigDict(frozen=True, strict=True)

    sensor_id: str = Field(
        default="UGLD-001",
        description="Unique sensor identifier for audit trail.",
    )
    trigger_threshold_db: float = Field(
        default=74.0,
        gt=0.0,
        description=("Minimum SPL (dB) to trigger alarm at sensor. Typical: 65-80 dB SPL depending on manufacturer."),
    )
    background_noise_db: float = Field(
        default=60.0,
        ge=0.0,
        description=(
            "Ambient ultrasonic noise floor at installation point (dB SPL). "
            "MUST come from site survey or conservative estimate — NOT a "
            "sensor property. Overriding with optimistic values is a "
            "safety-critical decision requiring FPE sign-off."
        ),
    )
    center_frequency_hz: float = Field(
        default=_DEFAULT_UGLD_FREQUENCY_HZ,
        gt=0.0,
        description=(
            "Sensor center operating frequency (Hz). Determines detection "
            "range via atmospheric attenuation. 40 kHz is most common for "
            "commercial UGLD (General Monitors Gassonic, MSA Senscient)."
        ),
    )
    directivity_deg: float = Field(
        default=360.0,
        gt=0.0,
        le=360.0,
        description=(
            "Sensor directivity angle (degrees). 360 = omnidirectional "
            "(typical for UGLD). Values < 360 indicate directional sensors."
        ),
    )


class AcousticPropagation(BaseModel):
    """Acoustic propagation model from leak source to UGLD sensor.

    Models free-field (no obstructions) spherical propagation of ultrasonic
    noise from a pressurized gas leak. The three physical effects are:

    1. Geometric Spreading (Inverse Square Law):
         SPL(R) = SPL(1m) - 20 * log10(R)
       Where R is distance in meters from the leak source.
       Assumes point source at 1m reference distance (standard for UGLD specs).

    2. Atmospheric Absorption (Frequency Dependent):
         Final_SPL(R) = SPL(R) - (alpha * R)
       Where alpha comes from ISO 9613-1:1993 and varies dramatically
       with frequency (0.12 dB/m at 25 kHz vs 5.5 dB/m at 100 kHz).

    3. Speed of Sound (Temperature Dependent):
         c = 331.3 * sqrt(1 + T/273.15)
       Used for propagation delay calculations (future Ray Tracing phase).

    The temp_c field MUST be consistent with EnvironmentalContext.ambient_temp_c
    to avoid Dual-Path Inconsistency (the V22 purge eliminated this class of
    bug for vapor density; we must not reintroduce it for acoustics).

    Reference: ISO 9613-1:1993, IEC 60079-29-4
    """

    model_config = ConfigDict(frozen=True, strict=True)

    leak_spl_at_1m: float = Field(
        ...,
        gt=0.0,
        description=(
            "Source noise level of the leak at 1 meter reference distance "
            "(dB SPL). Depends on gas pressure, orifice size, and gas type. "
            "Typical: 85-110 dB SPL at 1m for pressurized gas releases."
        ),
    )
    distance_meters: float = Field(
        ...,
        gt=0.0,
        description="Distance from leak source to UGLD sensor (meters).",
    )
    center_frequency_hz: float = Field(
        default=_DEFAULT_UGLD_FREQUENCY_HZ,
        gt=0.0,
        description=(
            "Center frequency of the ultrasonic signal (Hz). Must match "
            "the sensor's operating frequency for accurate attenuation."
        ),
    )
    temp_c: float = Field(
        default=40.0,
        ge=-40.0,
        le=85.0,
        description=(
            "Ambient temperature (C). MUST be consistent with "
            "EnvironmentalContext.ambient_temp_c to prevent Dual-Path "
            "Inconsistency. Default 40C = typical industrial indoor "
            "(matches EnvironmentalContext default)."
        ),
    )
    relative_humidity_pct: float = Field(
        default=50.0,
        ge=0.0,
        le=100.0,
        description="Relative humidity (%). Affects atmospheric attenuation.",
    )

    # ── Computed fields (set by model_validator) ──
    speed_of_sound_mps: float = Field(
        default=0.0,
        init=False,
        description="Computed speed of sound (m/s).",
    )
    geometric_loss_db: float = Field(
        default=0.0,
        init=False,
        description="Computed geometric spreading loss (dB).",
    )
    atmospheric_loss_db: float = Field(
        default=0.0,
        init=False,
        description="Computed atmospheric absorption loss (dB).",
    )
    final_spl_db: float = Field(
        default=0.0,
        init=False,
        description="Computed SPL at sensor position (dB SPL).",
    )
    alpha_db_per_m: float = Field(
        default=0.0,
        init=False,
        description="Computed atmospheric attenuation coefficient (dB/m).",
    )

    @model_validator(mode="after")
    def compute_acoustics(self) -> AcousticPropagation:
        """Compute all acoustic propagation values deterministically."""
        # 1. Temperature-dependent speed of sound (ISO 9613-1 §5)
        #    c = 331.3 * sqrt(1 + T/273.15)
        #    At 20C: c ≈ 343.2 m/s
        #    At 40C: c ≈ 354.7 m/s
        sos = 331.3 * math.sqrt(1.0 + (self.temp_c / 273.15))

        # 2. Geometric Spreading — Inverse Square Law
        #    SPL(R) = SPL(1m) - 20 * log10(R)
        #    Reference distance = 1m (standard for UGLD specifications)
        #    At R=2m: -6.02 dB (6 dB per doubling — the classic rule)
        #    At R=10m: -20.0 dB
        #    At R=100m: -40.0 dB
        geo_loss = 20.0 * math.log10(self.distance_meters)
        spl_after_geo = self.leak_spl_at_1m - geo_loss

        # 3. Atmospheric Absorption — ISO 9613-1 (frequency-dependent!)
        #    NOT a flat 0.5 dB/m — that would be physically wrong.
        #    At 40 kHz: alpha ≈ 0.5 dB/m → 15m distance = 7.5 dB loss
        #    At 100 kHz: alpha ≈ 5.5 dB/m → 15m distance = 82.5 dB loss!
        alpha = atmospheric_attenuation_db_per_m(
            center_frequency_hz=self.center_frequency_hz,
            temp_c=self.temp_c,
            relative_humidity_pct=self.relative_humidity_pct,
        )
        atm_loss = alpha * self.distance_meters

        # 4. Final SPL at sensor position
        final_spl = spl_after_geo - atm_loss

        # Set computed fields (frozen model — use object.__setattr__)
        object.__setattr__(self, "speed_of_sound_mps", round(sos, 1))
        object.__setattr__(self, "geometric_loss_db", round(geo_loss, 1))
        object.__setattr__(self, "atmospheric_loss_db", round(atm_loss, 1))
        object.__setattr__(self, "alpha_db_per_m", round(alpha, 4))
        object.__setattr__(self, "final_spl_db", round(final_spl, 1))
        return self


class UGLDTriggerResult(BaseModel):
    """Structured result of UGLD trigger check.

    Returns more than just triggered/not-triggered — provides the full
    acoustic analysis for audit trail and engineering review. This follows
    the same principle as AudibilityResult in acoustic_calculator.py:
    in a life-safety system, a boolean return is insufficient.

    Fields:
        triggered: Whether the sensor will detect the leak.
        final_spl_db: Computed SPL at the sensor position (dB SPL).
        snr_db: Signal-to-Noise Ratio (Final_SPL - Background_Noise).
        margin_to_threshold_db: Margin above trigger threshold.
        margin_to_snr_db: Margin above SNR requirement.
        fail_reason: If not triggered, which condition failed.

    Reference: ISA-TR 84.00.07, IEC 61508 SIL verification
    """

    model_config = ConfigDict(frozen=True, strict=True)

    triggered: bool
    final_spl_db: float
    background_noise_db: float
    trigger_threshold_db: float
    snr_db: float = Field(
        description="Signal-to-Noise Ratio = final_spl_db - background_noise_db",
    )
    margin_to_threshold_db: float = Field(
        description="Margin above trigger threshold = final_spl_db - trigger_threshold_db",
    )
    margin_to_snr_db: float = Field(
        description=("Margin above SNR requirement = snr_db - 6 dB minimum. Negative = insufficient SNR."),
    )
    fail_reason: Optional[str] = Field(
        default=None,
        description="If not triggered, which condition failed and why.",
    )


# ===========================================================================
# Core Detection Logic
# ===========================================================================


def check_ugld_trigger(
    propagation: AcousticPropagation,
    sensor: UltrasonicSensor,
) -> UGLDTriggerResult:
    """Check whether a UGLD sensor will detect a gas leak based on acoustic physics.

    The sensor triggers ONLY if BOTH conditions are met:
      1. Final SPL >= Sensor Trigger Threshold (hardware limit)
      2. Final SPL >= Background Noise + 6 dB (SNR requirement)

    Both conditions are AND-ed because:
      - Meeting threshold but not SNR = false alarm risk
      - Meeting SNR but not threshold = below sensor sensitivity

    Args:
        propagation: AcousticPropagation model with computed SPL at sensor.
        sensor: UltrasonicSensor model with threshold and noise specs.

    Returns:
        UGLDTriggerResult with triggered status, margins, and fail reason.

    Reference: ISA-TR 84.00.07 §4.3, IEC 61252:1993

    """
    final_spl = propagation.final_spl_db
    bg_noise = sensor.background_noise_db
    threshold = sensor.trigger_threshold_db

    snr = final_spl - bg_noise
    margin_threshold = final_spl - threshold
    margin_snr = snr - _MIN_SNR_DB

    # Both conditions must be met (AND logic)
    threshold_met = final_spl >= threshold
    snr_met = snr >= _MIN_SNR_DB
    triggered = threshold_met and snr_met

    # Determine fail reason if not triggered
    fail_reason: Optional[str] = None
    if not triggered:
        reasons = []
        if not threshold_met:
            reasons.append(
                f"Final SPL ({final_spl:.1f} dB) below trigger threshold "
                f"({threshold:.1f} dB). Deficit: {abs(margin_threshold):.1f} dB."
            )
        if not snr_met:
            reasons.append(
                f"SNR ({snr:.1f} dB) below minimum {_MIN_SNR_DB:.0f} dB. "
                f"Final SPL ({final_spl:.1f} dB) - Background ({bg_noise:.1f} dB) "
                f"= {snr:.1f} dB. Deficit: {abs(margin_snr):.1f} dB."
            )
        fail_reason = " | ".join(reasons)

    return UGLDTriggerResult(
        triggered=triggered,
        final_spl_db=final_spl,
        background_noise_db=bg_noise,
        trigger_threshold_db=threshold,
        snr_db=round(snr, 1),
        margin_to_threshold_db=round(margin_threshold, 1),
        margin_to_snr_db=round(margin_snr, 1),
        fail_reason=fail_reason,
    )


def max_detection_range_m(
    leak_spl_at_1m: float,
    sensor: UltrasonicSensor,
    temp_c: float = 40.0,
    relative_humidity_pct: float = 50.0,
) -> float:
    """Calculate the maximum detection range of a UGLD sensor for a given leak.

    Uses binary search to find the distance at which the sensor can still
    detect the leak (both threshold and SNR conditions met).

    This is the UGLD equivalent of get_speaker_coverage_radius() in
    acoustic_calculator.py — it provides the maximum effective range
    for sensor placement optimization.

    Args:
        leak_spl_at_1m: Source SPL at 1m reference distance (dB SPL).
        sensor: UltrasonicSensor specification.
        temp_c: Ambient temperature (C).
        relative_humidity_pct: Relative humidity (%).

    Returns:
        Maximum detection range in meters. 0.0 if leak cannot be detected
        even at 1m distance.

    Reference: ISA-TR 84.00.07 §4.3.2

    """
    # Quick check: can the sensor detect the leak at 1m?
    prop_1m = AcousticPropagation(
        leak_spl_at_1m=leak_spl_at_1m,
        distance_meters=1.0,
        center_frequency_hz=sensor.center_frequency_hz,
        temp_c=temp_c,
        relative_humidity_pct=relative_humidity_pct,
    )
    result_1m = check_ugld_trigger(prop_1m, sensor)
    if not result_1m.triggered:
        return 0.0

    # Binary search for maximum compliant distance
    lo, hi = 1.0, 500.0  # Search between 1m and 500m
    best_range = 1.0

    for _ in range(50):  # ~50 iterations gives ~0.01m precision
        mid = (lo + hi) / 2.0
        prop = AcousticPropagation(
            leak_spl_at_1m=leak_spl_at_1m,
            distance_meters=mid,
            center_frequency_hz=sensor.center_frequency_hz,
            temp_c=temp_c,
            relative_humidity_pct=relative_humidity_pct,
        )
        result = check_ugld_trigger(prop, sensor)

        if result.triggered:
            best_range = mid
            lo = mid
        else:
            hi = mid

    return round(best_range, 2)


# ===========================================================================
# Speed of Sound Utility
# ===========================================================================


def speed_of_sound(temp_c: float) -> float:
    """Calculate the speed of sound in air as a function of temperature.

    c = 331.3 * sqrt(1 + T/273.15)

    Reference: ISO 9613-1:1993 §5, ANSI S1.26-1995

    Args:
        temp_c: Temperature in degrees Celsius.

    Returns:
        Speed of sound in m/s.

    """
    return round(331.3 * math.sqrt(1.0 + (temp_c / 273.15)), 1)


__all__ = [
    # Enums
    "UGLDFrequencyBand",
    # Models
    "UltrasonicSensor",
    "AcousticPropagation",
    "UGLDTriggerResult",
    # Functions
    "check_ugld_trigger",
    "atmospheric_attenuation_db_per_m",
    "max_detection_range_m",
    "speed_of_sound",
    # Constants
    "_DEFAULT_UGLD_FREQUENCY_HZ",
    "_MIN_SNR_DB",
    "_ISO_9613_ALPHA_20C_50RH",
]
