server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

ingester:
  max_block_duration: 30m
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1

compactor:
  compaction:
    block_retention: 48h

storage:
  trace:
    backend: local
    local:
      path: /tempo/traces
    wal:
      path: /tempo/wal
    pool:
      max_workers: 100
      queue_depth: 10000

querier:
  max_concurrent_queries: 20

metrics_generator:
  registry:
    collection_interval: 15s
  storage:
    path: /tempo/generator
  traces_storage:
    path: /tempo/generator/traces

overrides:
  defaults:
    metrics_generator:
      processors: ['service-graphs', 'span-metrics']
