"""
marine/integration/scada_bridge.py — SCADA/ADMS Integration
=============================================================
Implements the "Integration-SCADA" module from the marine agent prompt.

Bridges the marine fire-safety system to shipboard SCADA/ADMS via:
    - MQTT (lightweight, ideal for IoT detectors)
    - OPC-UA (industrial standard, semantic-rich)
    - Modbus TCP (legacy support for older shipboard PLCs)

Topics/tags follow the unified schema:
    ship/{imo}/fire/alarm/{zone_id}
    ship/{imo}/fire/extinguish/{zone_id}
    ship/{imo}/power/ups/status
    ship/{imo}/power/insulation/resistance_kohm

Supports PyScada (Python/Django), Scada-LTS (Java), and JSON-SCADA (Go).
"""
from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, cast

import yaml


@dataclass
class SCADATag:
    """One SCADA tag (MQTT topic / OPC-UA node / Modbus register)."""

    tag_id: str
    zone_id: str
    tag_type: str               # "alarm", "extinguish", "power", "diagnostic"
    protocol: str               # "mqtt", "opcua", "modbus"
    address: str                # MQTT topic / OPC-UA node ID / Modbus register
    data_type: str = "BOOL"     # BOOL, INT, REAL, STRING
    description: str = ""
    unit: str = ""              # Engineering unit


def build_mqtt_topics(imo: str, zone_ids: list[str]) -> list[SCADATag]:
    """Generate the canonical MQTT topic tree for a ship."""
    tags: list[SCADATag] = []
    for zid in zone_ids:
        tags.append(SCADATag(
            tag_id=f"alarm_{zid}", zone_id=zid, tag_type="alarm",
            protocol="mqtt",
            address=f"ship/{imo}/fire/alarm/{zid}",
            description=f"Fire alarm status for zone {zid}",
        ))
        tags.append(SCADATag(
            tag_id=f"extinguish_{zid}", zone_id=zid, tag_type="extinguish",
            protocol="mqtt",
            address=f"ship/{imo}/fire/extinguish/{zid}",
            description=f"Extinguishing release status for zone {zid}",
        ))
    # Power/UPS
    tags.append(SCADATag(
        tag_id="ups_status", zone_id="ship", tag_type="power",
        protocol="mqtt", address=f"ship/{imo}/power/ups/status",
        data_type="STRING", description="UPS operational status",
    ))
    tags.append(SCADATag(
        tag_id="insulation", zone_id="ship", tag_type="power",
        protocol="mqtt", address=f"ship/{imo}/power/insulation/resistance_kohm",
        data_type="REAL", unit="kΩ", description="Insulation resistance (IEC 60092-504)",
    ))
    return tags


def build_pyscada_yaml(tags: list[SCADATag], broker: str = "mqtt://localhost:1883") -> str:
    """Generate a PyScada-compatible YAML configuration using yaml.safe_dump."""
    mqtt_topics = [t.address for t in tags if t.protocol == "mqtt"]
    tag_list = [
        {
            "id": t.tag_id,
            "zone": t.zone_id,
            "type": t.tag_type,
            "data_type": t.data_type,
            **({"unit": t.unit} if t.unit else {}),
        }
        for t in tags
    ]
    config = {
        "mqtt": {
            "broker": broker,
            "topics": mqtt_topics,
        },
        "tags": tag_list,
    }
    header = "# PyScada configuration — auto-generated by marine.integration.scada_bridge\n"
    return header + cast(str, yaml.safe_dump(config, sort_keys=False, default_flow_style=False))


def build_opcua_node_ids(tags: list[SCADATag], ns: int = 2) -> list[dict[str, Any]]:
    """Generate OPC-UA node IDs (namespace 2 = vendor-specific)."""
    return [
        {
            "tag_id": t.tag_id,
            "node_id": f"ns={ns};s=Ship.{t.zone_id}.{t.tag_type}",
            "data_type": t.data_type,
            "description": t.description,
        }
        for t in tags
    ]


def build_modbus_registers(tags: list[SCADATag], start_addr: int = 40001) -> list[dict[str, Any]]:
    """
    Map tags to Modbus holding registers (FC=03).

    BUGFIX v2: previously assigned a uniform 2 registers per non-BOOL tag,
    which is wrong for INT (1 register, 16-bit) and far too few for STRING
    (needs ~16 registers for typical status text). Now uses correct per-type
    widths based on Modbus Application Data Unit conventions:
      - BOOL → 1 register (packed as bit 0; better to use coils FC=01 but
        we keep FC=03 for consistency with mixed-type tag lists)
      - INT  → 1 register (16-bit signed)
      - REAL → 2 registers (32-bit IEEE 754 float, big-endian word order)
      - STRING → 16 registers (32 chars at 2 chars/register)
    """
    # Per-type register width.
    REG_WIDTH = {
        "BOOL": 1,
        "INT": 1,
        "REAL": 2,
        "STRING": 16,
    }

    registers = []
    addr = start_addr
    for t in tags:
        width = REG_WIDTH.get(t.data_type, 2)
        registers.append({
            "tag_id": t.tag_id,
            "register": addr,
            "data_type": t.data_type,
            "width": width,
            "description": t.description,
        })
        addr += width
    return registers


def dashboard_payload(
    imo: str,
    zones_status: dict[str, str],
    timestamp: str | None = None,
) -> dict[str, Any]:
    """
    Build a JSON payload for the safety dashboard.

    BUGFIX v2: previously hardcoded `"timestamp": "2026-06-18T00:00:00Z"`
    with a comment "caller fills actual" but no parameter existed — every
    payload carried the same fake timestamp. Now accepts an explicit
    `timestamp` parameter (ISO 8601 with Z suffix), defaulting to the
    current UTC time so payloads are always correctly time-stamped.
    """
    if timestamp is None:
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return {
        "ship_imo": imo,
        "timestamp": timestamp,
        "zones": [
            {"zone_id": zid, "status": s} for zid, s in zones_status.items()
        ],
        "summary": {
            "total_zones": len(zones_status),
            "alarms": sum(1 for s in zones_status.values() if s == "alarm"),
            "faults": sum(1 for s in zones_status.values() if s == "fault"),
            "normal": sum(1 for s in zones_status.values() if s == "normal"),
        },
    }


__all__ = [
    "SCADATag",
    "build_modbus_registers",
    "build_mqtt_topics",
    "build_opcua_node_ids",
    "build_pyscada_yaml",
    "dashboard_payload",
]
