"""
marine/integration/scada_bridge.py — SCADA/ADMS Integration
=============================================================
Implements the "Integration-SCADA" module from the marine agent prompt.

Bridges the marine fire-safety system to shipboard SCADA/ADMS via:
    - MQTT (lightweight, ideal for IoT detectors)
    - OPC-UA (industrial standard, semantic-rich)
    - Modbus TCP (legacy support for older shipboard PLCs)

Topics/tags follow the unified schema:
    ship/{imo}/fire/alarm/{zone_id}
    ship/{imo}/fire/extinguish/{zone_id}
    ship/{imo}/power/ups/status
    ship/{imo}/power/insulation/resistance_kohm

Supports PyScada (Python/Django), Scada-LTS (Java), and JSON-SCADA (Go).
"""
from __future__ import annotations
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class SCADATag:
    """One SCADA tag (MQTT topic / OPC-UA node / Modbus register)."""
    tag_id: str
    zone_id: str
    tag_type: str               # "alarm", "extinguish", "power", "diagnostic"
    protocol: str               # "mqtt", "opcua", "modbus"
    address: str                # MQTT topic / OPC-UA node ID / Modbus register
    data_type: str = "BOOL"     # BOOL, INT, REAL, STRING
    description: str = ""
    unit: str = ""              # Engineering unit


def build_mqtt_topics(imo: str, zone_ids: List[str]) -> List[SCADATag]:
    """Generate the canonical MQTT topic tree for a ship."""
    tags: List[SCADATag] = []
    for zid in zone_ids:
        tags.append(SCADATag(
            tag_id=f"alarm_{zid}", zone_id=zid, tag_type="alarm",
            protocol="mqtt",
            address=f"ship/{imo}/fire/alarm/{zid}",
            description=f"Fire alarm status for zone {zid}",
        ))
        tags.append(SCADATag(
            tag_id=f"extinguish_{zid}", zone_id=zid, tag_type="extinguish",
            protocol="mqtt",
            address=f"ship/{imo}/fire/extinguish/{zid}",
            description=f"Extinguishing release status for zone {zid}",
        ))
    # Power/UPS
    tags.append(SCADATag(
        tag_id="ups_status", zone_id="ship", tag_type="power",
        protocol="mqtt", address=f"ship/{imo}/power/ups/status",
        data_type="STRING", description="UPS operational status",
    ))
    tags.append(SCADATag(
        tag_id="insulation", zone_id="ship", tag_type="power",
        protocol="mqtt", address=f"ship/{imo}/power/insulation/resistance_kohm",
        data_type="REAL", unit="kΩ", description="Insulation resistance (IEC 60092-504)",
    ))
    return tags


def build_pyscada_yaml(tags: List[SCADATag], broker: str = "mqtt://localhost:1883") -> str:
    """Generate a PyScada-compatible YAML configuration."""
    lines = [
        "# PyScada configuration — auto-generated by marine.integration.scada_bridge",
        f"mqtt:",
        f"  broker: {broker}",
        f"  topics:",
    ]
    for t in tags:
        if t.protocol == "mqtt":
            lines.append(f"    - {t.address}")
    lines.append(f"tags:")
    for t in tags:
        lines.append(f"  - id: {t.tag_id}")
        lines.append(f"    zone: {t.zone_id}")
        lines.append(f"    type: {t.tag_type}")
        lines.append(f"    data_type: {t.data_type}")
        if t.unit:
            lines.append(f"    unit: {t.unit}")
    return "\n".join(lines)


def build_opcua_node_ids(tags: List[SCADATag], ns: int = 2) -> List[Dict[str, Any]]:
    """Generate OPC-UA node IDs (namespace 2 = vendor-specific)."""
    return [
        {
            "tag_id": t.tag_id,
            "node_id": f"ns={ns};s=Ship.{t.zone_id}.{t.tag_type}",
            "data_type": t.data_type,
            "description": t.description,
        }
        for t in tags
    ]


def build_modbus_registers(tags: List[SCADATag], start_addr: int = 40001) -> List[Dict[str, Any]]:
    """Map tags to Modbus holding registers (FC=03)."""
    registers = []
    addr = start_addr
    for t in tags:
        registers.append({
            "tag_id": t.tag_id,
            "register": addr,
            "data_type": t.data_type,
            "description": t.description,
        })
        addr += 1 if t.data_type == "BOOL" else 2  # INT/REAL = 2 registers
    return registers


def dashboard_payload(imo: str, zones_status: Dict[str, str]) -> Dict[str, Any]:
    """Build a JSON payload for the safety dashboard."""
    return {
        "ship_imo": imo,
        "timestamp": "2026-06-18T00:00:00Z",  # caller fills actual
        "zones": [
            {"zone_id": zid, "status": s} for zid, s in zones_status.items()
        ],
        "summary": {
            "total_zones": len(zones_status),
            "alarms": sum(1 for s in zones_status.values() if s == "alarm"),
            "faults": sum(1 for s in zones_status.values() if s == "fault"),
            "normal": sum(1 for s in zones_status.values() if s == "normal"),
        },
    }


__all__ = [
    "SCADATag", "build_mqtt_topics", "build_pyscada_yaml",
    "build_opcua_node_ids", "build_modbus_registers", "dashboard_payload",
]
